In [1]:
import os
import sys
import tempfile
from ast import literal_eval

import tensorflow as tf

import fastestimator as fe
from fastestimator.architecture.retinanet import RetinaNet, get_fpn_anchor_box, get_target
from fastestimator.dataset.mscoco import load_data
from fastestimator.op import NumpyOp, TensorOp
from fastestimator.op.numpyop import ImageReader, ResizeImageAndBbox, TypeConverter
from fastestimator.op.tensorop import Loss, ModelOp, Pad, Rescale
from fastestimator.trace import ModelSaver

In [2]:
train_csv, val_csv, path = load_data(path='/data/hsiming/dataset/')

In [3]:
class String2List(NumpyOp):
    # this thing converts '[1, 2, 3]' into np.array([1, 2, 3])
    def forward(self, data, state):
        data = map(literal_eval, data)
        return data


class GenerateTarget(NumpyOp):
    def __init__(self, inputs=None, outputs=None, mode=None):
        super().__init__(inputs=inputs, outputs=outputs, mode=mode)
        self.anchorbox, _ = get_fpn_anchor_box(input_shape=(512, 512, 3))

    def forward(self, data, state):
        obj_label, x1, y1, width, height = data
        cls_gt, x1_gt, y1_gt, w_gt, h_gt = get_target(self.anchorbox, obj_label, x1, y1, width, height)
        return cls_gt, x1_gt, y1_gt, w_gt, h_gt


class RetinaLoss(Loss):
    def focal_loss(self, cls_gt_example, cls_pred_example, alpha=0.25, gamma=2.0):
        # cls_gt_example shape: [A], cls_pred_example shape: [A, K]
        num_classes = cls_pred_example.shape[-1]
        # gather the objects and background, discard the rest
        anchor_obj_idx = tf.where(tf.greater_equal(cls_gt_example, 0))
        anchor_obj_bg_idx = tf.where(tf.greater_equal(cls_gt_example, -1))
        anchor_obj_count = tf.cast(tf.shape(anchor_obj_idx)[0], tf.float32)
        cls_gt_example = tf.one_hot(cls_gt_example, num_classes)
        cls_gt_example = tf.gather_nd(cls_gt_example, anchor_obj_bg_idx)
        cls_pred_example = tf.gather_nd(cls_pred_example, anchor_obj_bg_idx)
        cls_gt_example = tf.reshape(cls_gt_example, (-1, 1))
        cls_pred_example = tf.reshape(cls_pred_example, (-1, 1))
        # compute the focal weight on each selected anchor box
        alpha_factor = tf.ones_like(cls_gt_example) * alpha
        alpha_factor = tf.where(tf.equal(cls_gt_example, 1), alpha_factor, 1 - alpha_factor)
        focal_weight = tf.where(tf.equal(cls_gt_example, 1), 1 - cls_pred_example, cls_pred_example)
        focal_weight = alpha_factor * focal_weight**gamma / anchor_obj_count
        cls_loss = tf.losses.BinaryCrossentropy(reduction='sum')(cls_gt_example,
                                                                 cls_pred_example,
                                                                 sample_weight=focal_weight)
        return cls_loss, anchor_obj_idx

    def smooth_l1(self, loc_gt_example, loc_pred_example, anchor_obj_idx, beta=0.1):
        """Return smooth l1 loss for box regesssion.

        Args:
            loc_gt_example (Tensor): Tensor of shape (padded=252, 4).
            loc_pred_example (Tensor): Tensor of shape (num_anchors, 4).
            anchor_obj_idx (Tensor): Indices of selected anchor box.

        Returns:
            float: Smooth l1 loss.
        """
        loc_pred = tf.gather_nd(loc_pred_example, anchor_obj_idx)  #anchor_obj_count x 4
        anchor_obj_count = tf.shape(loc_pred)[0]
        loc_gt = loc_gt_example[:anchor_obj_count]  #anchor_obj_count x 4
        loc_gt = tf.reshape(loc_gt, (-1, 1))
        loc_pred = tf.reshape(loc_pred, (-1, 1))
        loc_diff = tf.abs(loc_gt - loc_pred)
        cond = tf.less(loc_diff, beta)
        smooth_l1_loss = tf.where(cond, 0.5 * loc_diff**2 / beta, loc_diff - 0.5 * beta)
        smooth_l1_loss = tf.reduce_sum(smooth_l1_loss) / tf.cast(anchor_obj_count, tf.float32)
        return smooth_l1_loss

    def forward(self, data, state):
        cls_gt, x1_gt, y1_gt, w_gt, h_gt, cls_pred, loc_pred = data
        local_batch_size = state["local_batch_size"]
        focal_loss = []
        l1_loss = []
        total_loss = []
        for idx in range(local_batch_size):
            cls_gt_example = cls_gt[idx]
            x1_gt_example = x1_gt[idx]
            y1_gt_example = y1_gt[idx]
            w_gt_example = w_gt[idx]
            h_gt_example = h_gt[idx]
            loc_gt_example = tf.transpose(tf.stack([x1_gt_example, y1_gt_example, w_gt_example, h_gt_example]))
            cls_pred_example = cls_pred[idx]
            loc_pred_example = loc_pred[idx]
            focal_loss_example, anchor_obj_idx = self.focal_loss(cls_gt_example, cls_pred_example)
            smooth_l1_loss_example = self.smooth_l1(loc_gt_example, loc_pred_example, anchor_obj_idx)
            focal_loss.append(focal_loss_example)
            l1_loss.append(smooth_l1_loss_example)
        focal_loss = tf.stack(focal_loss)
        l1_loss = tf.stack(l1_loss)
        total_loss = focal_loss + l1_loss

        return total_loss, focal_loss, l1_loss

In [4]:
class PredictBox(TensorOp):
    def __init__(self,
                 inputs=None,
                 outputs=None,
                 mode=None,
                 input_shape=(512, 512, 3),
                 select_top_k=1000,
                 nms_max_outputs=100):
        super().__init__(inputs=inputs, outputs=outputs, mode=mode)
        self.input_shape = input_shape
        self.select_top_k = tf.cast(select_top_k, dtype=tf.int32)
        self.nms_max_outputs = nms_max_outputs

        all_anchors, num_anchors_per_level = get_fpn_anchor_box(input_shape=input_shape)
        self.all_anchors = tf.convert_to_tensor(all_anchors)
        self.num_anchors_per_level = tf.convert_to_tensor(num_anchors_per_level, dtype=tf.int32)

    def index_to_bool(self, indices, length):
        updates = tf.ones_like(indices, dtype=tf.bool)
        shape = tf.expand_dims(length, 0)
        is_selected = tf.scatter_nd(tf.cast(tf.expand_dims(indices, axis=-1), dtype=tf.int32), updates, shape)
        return is_selected

    def forward(self, data, state):
        """
        # state['local_batch_size']
        # cls_pred.shape = (8, 49104, 90)
        """

        pred = []
        gt = []

        # extract max score and its class label
        #cls_pred, deltas, label_gt, x1_gt, y1_gt, w_gt, h_gt = data
        cls_pred, deltas = data
        #label_gt = tf.convert_to_tensor(label_gt)
        #x1_gt = tf.convert_to_tensor(x1_gt)
        #y1_gt = tf.convert_to_tensor(y1_gt)
        #w_gt = tf.convert_to_tensor(w_gt)
        #h_gt = tf.convert_to_tensor(h_gt)

        labels = tf.cast(tf.argmax(cls_pred, axis=2), dtype=tf.int32)
        scores = tf.reduce_max(cls_pred, axis=2)

        # iterate over image
        for i in range(state['local_batch_size']):
            labels_per_image = labels[i]
            scores_per_image = scores[i]
            deltas_per_image = deltas[i]
            
            #keep_gt = tf.greater(label_gt[i], 0)
            #label_gt_per_image = label_gt[i][keep_gt]
            #x1_gt_per_image = x1_gt[i][keep_gt]
            #y1_gt_per_image = y1_gt[i][keep_gt]
            #w_gt_per_image = w_gt[i][keep_gt]
            #h_gt_per_image = h_gt[i][keep_gt]

            selected_deltas_per_image = tf.constant([], shape=(0, 4))
            selected_labels_per_image = tf.constant([], dtype=tf.int32)
            selected_scores_per_image = tf.constant([])
            selected_anchor_indices_per_image = tf.constant([], dtype=tf.int32)

            end_index = 0
            # iterate over each pyramid level
            for j in range(self.num_anchors_per_level.shape[0]):
                start_index = end_index
                end_index += self.num_anchors_per_level[j]
                anchor_indices = tf.range(start_index, end_index, dtype=tf.int32)

                level_scores = scores_per_image[start_index:end_index]
                level_deltas = deltas_per_image[start_index:end_index]
                level_labels = labels_per_image[start_index:end_index]

                # select top k
                if self.num_anchors_per_level[j] >= self.select_top_k:
                    # won't work without the tf.minimum
                    top_k = tf.math.top_k(level_scores, tf.minimum(self.num_anchors_per_level[j], self.select_top_k))
                    top_k_scores = top_k.values
                    top_k_indices = tf.add(top_k.indices, [start_index])
                else:
                    top_k_scores = level_scores
                    top_k_indices = anchor_indices

                # filter out low score
                is_high_score = tf.greater(top_k_scores, 0.05)
                selected_indices = tf.boolean_mask(top_k_indices, is_high_score)
                is_selected = self.index_to_bool(tf.subtract(selected_indices, [start_index]),
                                                 self.num_anchors_per_level[j])

                # combine all pyramid levels
                selected_deltas_per_image = tf.concat(
                    [selected_deltas_per_image, tf.boolean_mask(level_deltas, is_selected)], axis=0)
                selected_scores_per_image = tf.concat(
                    [selected_scores_per_image, tf.boolean_mask(level_scores, is_selected)], axis=0)
                selected_labels_per_image = tf.concat(
                    [selected_labels_per_image, tf.boolean_mask(level_labels, is_selected)], axis=0)
                selected_anchor_indices_per_image = tf.concat(
                    [selected_anchor_indices_per_image, tf.boolean_mask(anchor_indices, is_selected)], axis=0)

            # delta -> (x1, y1, w, h)
            anchor_mask = self.index_to_bool(selected_anchor_indices_per_image, self.all_anchors.shape[0])
            x1 = (selected_deltas_per_image[:, 0] * tf.boolean_mask(
                self.all_anchors, anchor_mask)[:, 2]) + tf.boolean_mask(self.all_anchors, anchor_mask)[:, 0]
            y1 = (selected_deltas_per_image[:, 1] * tf.boolean_mask(
                self.all_anchors, anchor_mask)[:, 3]) + tf.boolean_mask(self.all_anchors, anchor_mask)[:, 1]
            w = tf.math.exp(selected_deltas_per_image[:, 2]) * tf.boolean_mask(self.all_anchors, anchor_mask)[:, 2]
            h = tf.math.exp(selected_deltas_per_image[:, 3]) * tf.boolean_mask(self.all_anchors, anchor_mask)[:, 3]
            x2 = x1 + w
            y2 = y1 + h

            # nms
            boxes_per_image = tf.stack([y1, x1, y2, x2], axis=1)
            nms_indices = tf.image.non_max_suppression(boxes_per_image, selected_scores_per_image, self.nms_max_outputs)

            nms_boxes = tf.gather(boxes_per_image, nms_indices)
            final_scores = tf.gather(selected_scores_per_image, nms_indices)
            final_labels = tf.gather(selected_labels_per_image, nms_indices)

            x1 = tf.clip_by_value(nms_boxes[:, 1], clip_value_min=0, clip_value_max=self.input_shape[1])
            y1 = tf.clip_by_value(nms_boxes[:, 0], clip_value_min=0, clip_value_max=self.input_shape[0])
            w = tf.clip_by_value(nms_boxes[:, 3], clip_value_min=0, clip_value_max=self.input_shape[1]) - x1
            h = tf.clip_by_value(nms_boxes[:, 2], clip_value_min=0, clip_value_max=self.input_shape[0]) - y1

            final_boxes = tf.stack([x1, y1, w, h], axis=1)

            # combine image results into batch
            image_results = tf.concat([
                tf.pad(final_boxes, [[0, 0], [1, 0]], constant_values=i),
                tf.cast(tf.expand_dims(final_labels, axis=1), dtype=tf.float32),
                tf.expand_dims(final_scores, axis=1)
            ],
                                      axis=1)

            #image_gt = tf.transpose(
            #    tf.concat([
            #        tf.stack([i * tf.ones_like(x1_gt_per_image), x1_gt_per_image]),
            #        tf.expand_dims(y1_gt_per_image, axis=0),
            #        tf.expand_dims(w_gt_per_image, axis=0),
            #        tf.expand_dims(h_gt_per_image, axis=0),
            #        tf.expand_dims(label_gt_per_image, axis=0)
            #    ],
            #              axis=0))
            pred.append(image_results)
            #gt.append(image_gt)
            tf.print(final_scores)
        return tf.concat(pred, axis=0)  #, tf.concat(gt, axis=0)

In [5]:
model_dir = '/data/hsiming/mscoco_model/'
writer = fe.RecordWriter(
    save_dir=os.path.join(path, "retinanet_coco_small"),
    train_data='/data/hsiming/dataset/MSCOCO2017/train_object_small.csv',
    validation_data='/data/hsiming/dataset/MSCOCO2017/train_object_small.csv',
    ops=[
        ImageReader(inputs="image", parent_path=path, outputs="image"),
        String2List(inputs=["x1", "y1", "width", "height", "obj_label"],
                    outputs=["x1", "y1", "width", "height", "obj_label"]),
        ResizeImageAndBbox(target_size=(512, 512),
                           keep_ratio=True,
                           inputs=["image", "x1", "y1", "width", "height"],
                           outputs=["image", "x1", "y1", "width", "height"]),
        GenerateTarget(inputs=("obj_label", "x1", "y1", "width", "height"),
                       outputs=("cls_gt", "x1_gt", "y1_gt", "w_gt", "h_gt")),
        TypeConverter(target_type='int32', inputs=["id", "cls_gt"], outputs=["id", "cls_gt"]),
        TypeConverter(target_type='float32',
                      inputs=["x1_gt", "y1_gt", "w_gt", "h_gt"],
                      outputs=["x1_gt", "y1_gt", "w_gt", "h_gt"])
    ],
    compression="GZIP",
    write_feature=["image", "id", "cls_gt", "x1_gt", "y1_gt", "w_gt", "h_gt"])

# prepare pipeline
pipeline = fe.Pipeline(
    batch_size=8,
    padded_batch=True,
    data=writer,
    ops=[
        Rescale(inputs="image", outputs="image"),
        Pad(padded_shape=[190], inputs=["x1_gt", "y1_gt", "w_gt", "h_gt"], outputs=["x1_gt", "y1_gt", "w_gt", "h_gt"])
    ])

# prepare network
model = fe.build(model_def=lambda: RetinaNet(input_shape=(512, 512, 3), num_classes=90),
                 model_name="retinanet",
                 optimizer=tf.optimizers.Adam(learning_rate=0.0002),
                 loss_name="total_loss")
network = fe.Network(ops=[
    ModelOp(inputs="image", model=model, outputs=["cls_pred", "loc_pred"]),
    PredictBox(inputs=["cls_pred", "loc_pred"],
               outputs=("pred"),
               mode="eval"),
    RetinaLoss(inputs=("cls_gt", "x1_gt", "y1_gt", "w_gt", "h_gt", "cls_pred", "loc_pred"),
               outputs=("total_loss", "focal_loss", "l1_loss"))
])

# prepare estimator
estimator = fe.Estimator(
    network=network,
    pipeline=pipeline,
    epochs=200,
    #steps_per_epoch=2,
    log_steps=1,
    #validation_steps=2,
    traces=ModelSaver(model_name="retinanet", save_dir=model_dir, save_best=True))

In [6]:
estimator.fit()

    ______           __  ______     __  _                 __            
   / ____/___ ______/ /_/ ____/____/ /_(_)___ ___  ____ _/ /_____  _____
  / /_  / __ `/ ___/ __/ __/ / ___/ __/ / __ `__ \/ __ `/ __/ __ \/ ___/
 / __/ / /_/ (__  ) /_/ /___(__  ) /_/ / / / / / / /_/ / /_/ /_/ / /    
/_/    \__,_/____/\__/_____/____/\__/_/_/ /_/ /_/\__,_/\__/\____/_/     
                                                                        

FastEstimator: Reading non-empty directory: /data/hsiming/dataset/MSCOCO2017/retinanet_coco_small
FastEstimator: Found 50 examples for train in /data/hsiming/dataset/MSCOCO2017/retinanet_coco_small/train_summary0.json
FastEstimator: Found 50 examples for eval in /data/hsiming/dataset/MSCOCO2017/retinanet_coco_small/eval_summary0.json
[]
[]
[]
[]
[]
[]
[]
[]
FastEstimator-Start: step: 0; total_train_steps: 1200; retinanet_lr: 0.0002; 
FastEstimator-Train: step: 0; focal_loss: 2.1004574; l1_loss: 0.9493042; total_loss: 3.0497618; 
FastEstimator-Train: step:

FastEstimator-Train: step: 40; focal_loss: 1.0125945; l1_loss: 0.6951562; total_loss: 1.7077508; examples/sec: 31.8; progress: 3.3%; 
FastEstimator-Train: step: 41; focal_loss: 1.6896902; l1_loss: 0.5435516; total_loss: 2.2332416; examples/sec: 32.4; progress: 3.4%; 
[0.999990344 0.999976516 0.999874592 ... 0.0867998898 0.0821536779 0.074852705]
[0.999946356 0.999582052 0.998945355 ... 0.0637586117 0.0589213073 0.0526533127]
[0.998245716 0.997383 0.99127388 ... 0.0639478 0.0566522777 0.0512379706]
[0.999984 0.999952912 0.999782085 ... 0.0840135217 0.0801663399 0.0724467933]
[0.999999762 0.999999285 0.999997079 ... 0.239436626 0.236735612 0.173248261]
[0.99999 0.999966145 0.999850214 ... 0.10776028 0.0966772139 0.0939851105]
[0.998591065 0.994471669 0.987825155 ... 0.0586817861 0.0541267693 0.0511571467]
[0.998968244 0.997483611 0.992986321 ... 0.0565140843 0.0527821779 0.051310569]
[0.999959648 0.999933124 0.999650717 ... 0.087109983 0.0790414512 0.0789936781]
[0.998859763 0.996772289 

[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
FastEstimator-Eval: step: 66; epoch: 10; focal_loss: 1.7068847; l1_loss: 0.7050376; total_loss: 2.4119222; 
FastEstimator-Train: step: 66; focal_loss: 0.9251978; l1_loss: 0.4014777; total_loss: 1.3266757; examples/sec: 32.2; progress: 5.5%; 
FastEstimator-Train: step: 67; focal_loss: 0.901158; l1_loss: 0.4899395; total_loss: 1.3910975; examples/sec: 32.3; progress: 5.6%; 
FastEstimator-Train: step: 68; focal_loss: 0.9769981; l1_loss: 0.5195095; total_loss: 1.4965076; examples/sec: 32.0; progress: 5.7%; 
FastEstimator-Train: step: 69; focal_loss: 0.951048; l1_loss: 0.5391904; total_loss: 1.4902385; examples/sec: 31.9; progress: 5.8%; 
FastEstimator-Train: step: 70; focal_loss: 1.1865665; l1_loss: 0.4966197; total_loss: 1.6831862; examples/sec: 31.5; progress: 5.8%; 
FastEstimator-Train: step: 71; focal_loss: 0.855185; l1_loss: 0.3893334; total_loss: 1.2445185; examples/sec: 31.9; progress: 5.9%; 
[]
[]
[]
[]
[]
[

FastEstimator-Train: step: 109; focal_loss: 0.8596258; l1_loss: 0.505895; total_loss: 1.3655207; examples/sec: 32.1; progress: 9.1%; 
FastEstimator-Train: step: 110; focal_loss: 0.8301064; l1_loss: 0.3836161; total_loss: 1.2137225; examples/sec: 32.3; progress: 9.2%; 
FastEstimator-Train: step: 111; focal_loss: 0.712482; l1_loss: 0.3897237; total_loss: 1.1022058; examples/sec: 32.2; progress: 9.2%; 
FastEstimator-Train: step: 112; focal_loss: 0.6941641; l1_loss: 0.3090229; total_loss: 1.003187; examples/sec: 31.6; progress: 9.3%; 
FastEstimator-Train: step: 113; focal_loss: 0.8082272; l1_loss: 0.3516878; total_loss: 1.1599151; examples/sec: 32.0; progress: 9.4%; 
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
FastEstimator-Eval: step: 114; epoch: 18; focal_loss: 1.8645892; l1_loss: 0.6885447; total_loss: 2.5531337; 
FastEstimator-Train: step: 114; focal_loss: 0.7150674; l1_loss: 0.4032079; 

[0.0732933879 0.0667878091]
[0.0693983734 0.0635132492]
[0.0794959664 0.0718862116]
[0.0725059509 0.0661008954]
[0.0731957257 0.0666798949]
[0.0712218881 0.0649889708]
[0.0702788234 0.0643031299]
[0.0750010908 0.068380028]
[0.0754281878 0.0680479705]
[0.0702354908 0.0642284155]
[0.0698229074 0.063891083]
[0.0718272 0.0653479099]
[0.0712842941 0.0650559068]
[0.0756658316 0.0684907138]
[0.0703611374 0.0643287]
[0.0704133511 0.0643597245]
[0.0729327202 0.066041559]
[0.0759119093 0.0685941]
[0.0714818239 0.0651920736]
[0.0743719637 0.066973865]
[0.0703962147 0.064342171]
[0.0713973641 0.0652080178]
[0.0752164721 0.0685777068]
[0.0708459616 0.0647032]
[0.0751808584 0.0681744814]
FastEstimator-Eval: step: 144; epoch: 23; focal_loss: 1.6281838; l1_loss: 0.7138706; total_loss: 2.3420544; 
FastEstimator-Train: step: 144; focal_loss: 0.6102322; l1_loss: 0.2369818; total_loss: 0.847214; examples/sec: 32.2; progress: 12.0%; 
FastEstimator-Train: step: 145; focal_loss: 0.7052793; l1_loss: 0.2983068

FastEstimator-Train: step: 186; focal_loss: 0.5320952; l1_loss: 0.194546; total_loss: 0.726641; examples/sec: 32.3; progress: 15.5%; 
FastEstimator-Train: step: 187; focal_loss: 0.506256; l1_loss: 0.2154603; total_loss: 0.7217163; examples/sec: 31.9; progress: 15.6%; 
FastEstimator-Train: step: 188; focal_loss: 0.5634352; l1_loss: 0.1990896; total_loss: 0.7625247; examples/sec: 32.1; progress: 15.7%; 
FastEstimator-Train: step: 189; focal_loss: 0.6093622; l1_loss: 0.1759262; total_loss: 0.7852884; examples/sec: 32.0; progress: 15.8%; 
FastEstimator-Train: step: 190; focal_loss: 0.5703912; l1_loss: 0.1662356; total_loss: 0.7366268; examples/sec: 31.6; progress: 15.8%; 
FastEstimator-Train: step: 191; focal_loss: 0.5932364; l1_loss: 0.2074812; total_loss: 0.8007176; examples/sec: 32.5; progress: 15.9%; 
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
FastEstimator-Eval: step: 192; epoch: 31; f

[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
FastEstimator-Eval: step: 234; epoch: 38; focal_loss: 1.658595; l1_loss: 0.7092954; total_loss: 2.3678906; 
FastEstimator-Train: step: 234; focal_loss: 0.3408537; l1_loss: 0.1396355; total_loss: 0.4804892; examples/sec: 32.2; progress: 19.5%; 
FastEstimator-Train: step: 235; focal_loss: 0.5093234; l1_loss: 0.1835295; total_loss: 0.6928529; examples/sec: 32.5; progress: 19.6%; 
FastEstimator-Train: step: 236; focal_loss: 0.3864958; l1_loss: 0.0830109; total_loss: 0.4695068; examples/sec: 32.2; progress: 19.7%; 
FastEstimator-Train: step: 237; focal_loss: 0.497008; l1_loss: 0.1694269; total_loss: 0.6664349; examples/sec: 31.9; progress: 19.8%; 
FastEstimator-Train: step: 238; focal_loss: 0.4924298; l1_loss: 0.1985443; total_loss: 0.690974; examples/sec: 32.2; progress: 19.8%; 
FastEstimator-Train: step: 239; focal_loss: 0.428805; l1_loss: 0.1880541;

FastEstimator-Train: step: 280; focal_loss: 0.2793612; l1_loss: 0.1575928; total_loss: 0.436954; examples/sec: 31.5; progress: 23.3%; 
FastEstimator-Train: step: 281; focal_loss: 0.2382887; l1_loss: 0.1458648; total_loss: 0.3841535; examples/sec: 32.2; progress: 23.4%; 
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
FastEstimator-Eval: step: 282; epoch: 46; focal_loss: 1.9785182; l1_loss: 0.6995486; total_loss: 2.6780665; 
FastEstimator-Train: step: 282; focal_loss: 0.2050052; l1_loss: 0.1146727; total_loss: 0.319678; examples/sec: 32.1; progress: 23.5%; 
FastEstimator-Train: step: 283; focal_loss: 0.1906573; l1_loss: 0.0971853; total_loss: 0.2878426; examples/sec: 32.1; progress: 23.6%; 
FastEstimator-Train: step: 284; focal_loss: 0.2046748; l1_loss: 0.1197355; total_loss: 0.3244104; examples/sec: 32.4; progress: 23.7%; 
FastEstimator-Train: step: 285; focal_loss: 0.1842426; l1_loss: 0.133

FastEstimator-Train: step: 326; focal_loss: 0.1958224; l1_loss: 0.1085356; total_loss: 0.304358; examples/sec: 32.1; progress: 27.2%; 
FastEstimator-Train: step: 327; focal_loss: 0.1546651; l1_loss: 0.0749369; total_loss: 0.229602; examples/sec: 32.2; progress: 27.3%; 
FastEstimator-Train: step: 328; focal_loss: 0.1554606; l1_loss: 0.0643299; total_loss: 0.2197905; examples/sec: 32.2; progress: 27.3%; 
FastEstimator-Train: step: 329; focal_loss: 0.1940213; l1_loss: 0.0631352; total_loss: 0.2571565; examples/sec: 32.6; progress: 27.4%; 
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
FastEstimator-Eval: step: 330; epoch: 54; focal_loss: 1.918313; l1_loss: 0.6741193; total_loss: 2.5924327; 
FastEstimator-Train: step: 330; focal_loss: 0.1406052; l1_loss: 0.0813263; total_loss: 0.2219315; examples/sec: 32.4; progress: 27.5%; 
FastEstimator-Train: step: 331; focal_loss: 0.167948; l1_loss: 0.12760

FastEstimator-Train: step: 372; focal_loss: 0.2624774; l1_loss: 0.0821001; total_loss: 0.3445775; examples/sec: 32.2; progress: 31.0%; 
FastEstimator-Train: step: 373; focal_loss: 0.0770511; l1_loss: 0.0415404; total_loss: 0.1185915; examples/sec: 32.6; progress: 31.1%; 
FastEstimator-Train: step: 374; focal_loss: 0.0823488; l1_loss: 0.0488975; total_loss: 0.1312462; examples/sec: 31.6; progress: 31.2%; 
FastEstimator-Train: step: 375; focal_loss: 0.0758244; l1_loss: 0.0365799; total_loss: 0.1124042; examples/sec: 32.2; progress: 31.2%; 
FastEstimator-Train: step: 376; focal_loss: 0.1020073; l1_loss: 0.0606005; total_loss: 0.1626078; examples/sec: 32.2; progress: 31.3%; 
FastEstimator-Train: step: 377; focal_loss: 0.1155452; l1_loss: 0.0744528; total_loss: 0.189998; examples/sec: 32.1; progress: 31.4%; 
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[0.273067147 0.0624409914 0.0622786 0.0587450862]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]


FastEstimator-Train: step: 417; focal_loss: 0.1838224; l1_loss: 0.1356826; total_loss: 0.319505; examples/sec: 31.9; progress: 34.8%; 
FastEstimator-Train: step: 418; focal_loss: 0.0610779; l1_loss: 0.0949396; total_loss: 0.1560175; examples/sec: 32.2; progress: 34.8%; 
FastEstimator-Train: step: 419; focal_loss: 0.1267405; l1_loss: 0.084968; total_loss: 0.2117085; examples/sec: 31.7; progress: 34.9%; 
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[0.0519040823]
[]
[]
[]
[0.0727717578 0.0578161776]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[0.0685766935 0.0683392286 0.0600283742]
[]
[]
[]
[]
[]
[]
[0.0971180201 0.0767020881]
[]
[]
[]
[]
[]
FastEstimator-Eval: step: 420; epoch: 69; focal_loss: 1.9964268; l1_loss: 0.6021744; total_loss: 2.598601; 
FastEstimator-Train: step: 420; focal_loss: 0.1910856; l1_loss: 0.1239132; total_loss: 0.3149989; examples/sec: 31.8; progress: 35.0%; 
FastEstimator-Train: step: 421; focal_loss: 0.0549175; l1_loss: 0.0882239; total_loss: 0.1431414; examples

FastEstimator-Train: step: 454; focal_loss: 0.0371829; l1_loss: 0.0309856; total_loss: 0.0681686; examples/sec: 32.4; progress: 37.8%; 
FastEstimator-Train: step: 455; focal_loss: 0.0184703; l1_loss: 0.0299705; total_loss: 0.0484408; examples/sec: 31.8; progress: 37.9%; 
[]
[]
[0.0542688072]
[0.0616673231 0.0508593619]
[0.0968754292 0.0875514746 0.0735142529 ... 0.0584772229 0.0562558174 0.0541520715]
[0.0517039895]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[0.0713874102 0.0600259304]
[0.0552588701]
[]
[0.0669730902 0.0652269125]
[0.0706136227 0.0528715849]
[0.0534080267]
[]
[]
[0.117527932 0.103952348]
[0.0708145797]
[0.0684148669]
[]
[]
[]
[0.061343044]
[]
[]
[]
[]
[0.0576118529 0.0524584353]
[]
[]
[]
[]
[0.0541405082]
[]
[0.0569839478]
[0.105550557 0.0988538265 0.0679168105 0.0632809401 0.0602642596 0.0591736138]
FastEstimator-Eval: step: 456; epoch: 75; focal_loss: 1.978965; l1_loss: 0.5640296; total_loss: 2.5429945; 
FastEstimator-Train: step: 456; focal_loss: 0.053988; l1_loss: 0

[0.0596452653]
[]
[]
[0.0561652184]
[]
[0.0757437944 0.0587329865 0.0572862923 0.0569879711]
[0.284744531 0.262488484 0.232917726 ... 0.0594818 0.0570719242 0.0565716624]
[0.0517336428]
[]
[]
[0.0554404557]
[0.123104692 0.0794409513 0.0681119859 0.0522255898]
[0.0867781043 0.0752869546]
[0.200320035 0.163270116 0.152150631 ... 0.0621328354 0.0527431667 0.0504055619]
[0.0596161485]
[]
[]
[0.0525304377]
[]
[]
[]
[0.0570390522]
[]
[0.0640508831 0.0637672544]
[]
[]
[]
[0.0573661625]
[]
[0.0837484 0.0592174232 0.0558230579]
[]
[]
[0.106918246 0.0773898661 0.0560688674]
[0.125879049 0.0823273957]
[0.106348842 0.105233282 0.0672774 0.0599677861 0.0567598641]
[]
[]
[0.0866716504]
[0.0932399929]
[0.0970404148 0.0767920613 0.0709037483]
[0.0536907911]
[]
[]
[0.0806602836 0.0543613434]
[]
[]
[0.0568386912]
FastEstimator-Eval: step: 486; epoch: 80; focal_loss: 2.0083268; l1_loss: 0.5371264; total_loss: 2.5454533; 
FastEstimator-Train: step: 486; focal_loss: 0.0179025; l1_loss: 0.0425141; total_los

[0.0576451123 0.0515286326]
[]
[0.0800851882 0.0708044767 0.0691252947 0.0519917607]
[]
[0.0921362042 0.0577069223]
[0.143055767 0.0615266562]
[0.13686806 0.0922294259]
[0.151354015 0.133118957 0.0930716395 0.0861772 0.0813877 0.0725294948]
[]
[]
[0.222499073 0.0958429873]
[0.123989791]
FastEstimator-Eval: step: 510; epoch: 84; focal_loss: 1.9213766; l1_loss: 0.4879954; total_loss: 2.409372; 
FastEstimator-Train: step: 510; focal_loss: 0.0311881; l1_loss: 0.0467989; total_loss: 0.0779869; examples/sec: 32.4; progress: 42.5%; 
FastEstimator-Train: step: 511; focal_loss: 0.0261787; l1_loss: 0.0563311; total_loss: 0.0825098; examples/sec: 32.1; progress: 42.6%; 
FastEstimator-Train: step: 512; focal_loss: 0.0099472; l1_loss: 0.0539702; total_loss: 0.0639174; examples/sec: 32.1; progress: 42.7%; 
FastEstimator-Train: step: 513; focal_loss: 0.0137863; l1_loss: 0.0438854; total_loss: 0.0576717; examples/sec: 32.3; progress: 42.8%; 
FastEstimator-Train: step: 514; focal_loss: 0.0149047; l1_lo

[0.0749069452 0.0698005557 0.0675132871]
[]
[]
[0.109802783 0.068810761 0.0638430715 0.0622308552 0.0607531369]
[0.125419945 0.061770469 0.0596316457 0.0584091246 0.0512347817 0.050157249]
[0.0521358848]
[0.126890957 0.0771668255]
[]
[0.118693143 0.0802769959]
[]
[0.0956392586 0.0683182478 0.0629867911]
[]
[0.0505784154]
[0.069717139]
[]
[0.143980294 0.0994289815 0.0642589 0.0562269688 0.0530661941]
[0.405483127 0.382745206 0.287802041 ... 0.0594323277 0.0548437238 0.0535919964]
[0.0693743825 0.0515284538]
[]
[]
[0.111126006 0.101614684 0.0933566689 ... 0.056484431 0.0531408489 0.052233994]
[0.314218044 0.240303338 0.212854952 ... 0.0519712567 0.0506134927 0.0504033864]
[0.0846454203 0.0753679872]
[0.287835121 0.198907763 0.17116183 ... 0.0581835508 0.0564599335 0.0555751622]
[0.0961715 0.0806106925]
[]
[]
[0.0704305172]
[]
[]
[0.156478614 0.113008708]
[0.0964805782]
[]
[0.123099953 0.112387896 0.0688959956 ... 0.0560008287 0.0527002811 0.0504721105]
[0.0679951906]
[]
[0.161593765 0.07

[0.161205351 0.114719689]
[0.406248093 0.311497331 0.186728179 ... 0.0540984869 0.0530863106 0.0527803898]
[0.165196449 0.129729152 0.0601016283]
[]
[]
[0.0774965 0.0528152287]
[0.0874711275]
[0.0559204221]
[0.112556279]
[0.23849833 0.0596384406]
[]
[0.124181628 0.0846076906 0.0810028613 ... 0.0505721867 0.0504721701 0.0503532]
[0.0915232 0.053431958]
FastEstimator-Eval: step: 552; epoch: 91; focal_loss: 1.7283524; l1_loss: 0.4319094; total_loss: 2.1602619; 
FastEstimator-Train: step: 552; focal_loss: 0.0049156; l1_loss: 0.0328113; total_loss: 0.0377269; examples/sec: 31.9; progress: 46.0%; 
FastEstimator-Train: step: 553; focal_loss: 0.0098253; l1_loss: 0.0364231; total_loss: 0.0462483; examples/sec: 32.3; progress: 46.1%; 
FastEstimator-Train: step: 554; focal_loss: 0.0470584; l1_loss: 0.064352; total_loss: 0.1114104; examples/sec: 32.5; progress: 46.2%; 
FastEstimator-Train: step: 555; focal_loss: 0.008797; l1_loss: 0.0752941; total_loss: 0.0840911; examples/sec: 32.2; progress: 46.

FastEstimator-Train: step: 572; focal_loss: 0.0039025; l1_loss: 0.0403918; total_loss: 0.0442943; examples/sec: 32.3; progress: 47.7%; 
FastEstimator-Train: step: 573; focal_loss: 0.1352267; l1_loss: 0.0887334; total_loss: 0.22396; examples/sec: 32.5; progress: 47.8%; 
FastEstimator-Train: step: 574; focal_loss: 0.0643782; l1_loss: 0.0613947; total_loss: 0.1257729; examples/sec: 32.0; progress: 47.8%; 
FastEstimator-Train: step: 575; focal_loss: 0.0116735; l1_loss: 0.0975015; total_loss: 0.1091751; examples/sec: 31.5; progress: 47.9%; 
[0.0539368689 0.0513893068]
[0.14241007 0.101764977 0.100672901 0.0953822732 0.0878527761]
[0.211543292 0.0745975077]
[]
[0.238567621 0.225959957 0.180765152 ... 0.051040709 0.0505159795 0.0501969755]
[0.130783677 0.0905171]
[0.0530670583]
[0.449670523 0.306730628 0.237009346 0.0678166747 0.056915462 0.0545160174]
[0.294426471 0.173853427 0.124061763 ... 0.0595591366 0.0525990427 0.0522417724]
[0.0587967634]
[0.164374471 0.133550346 0.12891382 ... 0.0708

[0.39193356 0.127824783 0.0853924155 ... 0.0548253655 0.0547309518 0.0512434542]
[0.136331081 0.0804271102 0.0748140514 0.0613105 0.0519703329]
[0.230355918 0.128162771 0.0718303 0.0659736097]
[0.0817460716]
[0.254821837 0.179204881 0.104493618]
[0.350571096 0.112826347 0.0835089684 0.0655981898 0.058216542]
[0.146108806 0.112049967 0.0938916206 ... 0.0533958077 0.0526289642 0.0509883463]
[]
[0.105366051 0.104214609 0.103663236]
[0.0919245481 0.0551553071]
[]
[0.283366144 0.0945649743 0.0724476576 0.0673503876 0.0624683499]
[0.664865077 0.53344363 0.494829834 ... 0.0550586581 0.0546220243 0.0515293181]
[0.0775370598 0.0732691 0.0670248568 0.0505687296]
[0.0862831473 0.0632410645 0.0516828 0.0515810549]
[]
[0.185765862 0.172904849 0.116877377 ... 0.0540545285 0.0510566533 0.0504716039]
[0.870375276 0.806942523 0.527213335 ... 0.0515859127 0.0508424938 0.0502742827]
[0.11943233 0.0756718516]
FastEstimator-ModelSaver: Saving model to /data/hsiming/mscoco_model/retinanet_best_total_loss.h5

FastEstimator-Train: step: 605; focal_loss: 0.0216961; l1_loss: 0.0450097; total_loss: 0.0667058; examples/sec: 32.1; progress: 50.4%; 
[0.0740400553]
[0.644586444 0.471114635 0.288029969 ... 0.0595040321 0.0553143322 0.053287]
[0.808142722 0.79059875 0.443745434 ... 0.0508798957 0.0505978167 0.0504776835]
[0.183888793 0.136838138]
[0.84818697 0.556438506 0.462191641 ... 0.0548659861 0.0534223318 0.0500307679]
[0.198060483 0.183480531 0.149189681 ... 0.0807790756 0.0675616264 0.0577682853]
[0.0739621818 0.069516331 0.0606388152 0.0580234826]
[]
[0.163294524 0.0783735514 0.0770680606 ... 0.0571720898 0.0548748672 0.0531943738]
[0.085822016 0.0742535889]
[0.16855827 0.127053112 0.076241225 0.0755189657 0.0647428632 0.0628911555]
[0.224209875 0.158322304 0.107910156 0.102447 0.0640823841]
[0.481055051 0.126831234]
[0.124827266 0.0851430297 0.0827078819]
[0.275860101 0.273324668 0.210600227 ... 0.0502937734 0.0502873361 0.0500060022]
[0.218165517 0.190379918]
[0.0992807448 0.0855632126 0.0

[0.24437955 0.237897694 0.21967 ... 0.0556170344 0.0552357137 0.050699383]
[0.164538652 0.160071969]
[0.0680867732 0.0503178239]
[0.530835927 0.484932095 0.270740837 0.0917578936 0.0736799836 0.0542803109]
[0.357811928 0.357560575 0.349728078 ... 0.0530441403 0.0529876947 0.0502329171]
[0.0786236227]
[0.279638946 0.168292791 0.166639417 ... 0.0679416358 0.0568058789 0.0540697575]
[0.229669362 0.202953577 0.100221038]
[0.32693398 0.288475454 0.139288276 0.11133486 0.0878317952 0.0803086162]
[0.501402 0.132427305 0.112009734 ... 0.0558959842 0.0505066812 0.0502975881]
[0.240567774 0.185260773 0.151196092 0.111301243 0.08292225 0.0505020022]
[0.525537312 0.517275631 0.286937535 ... 0.0739107728 0.0564742386 0.0533095896]
[0.111852199 0.0666636527 0.0604133606 0.0551502705]
[0.106141597 0.0597401261]
[0.657068074 0.416701049 0.0846424103 0.0674446523]
[0.40717572]
[0.293058544 0.179199785 0.16685605 ... 0.0723373294 0.0609132946 0.0532069206]
[0.13211149 0.131061554 0.0864995122 0.07238224

[0.143191397 0.0715776086 0.070925 0.0530861914]
[0.289814264]
[0.222952604 0.0566757619]
[0.458432406 0.409231305 0.364371955 ... 0.0645175278 0.0551350713 0.053915292]
[0.731317043 0.401381522 0.296282709 ... 0.0529962182 0.0516398549 0.0514159799]
[0.357289076 0.216873616 0.129304528 0.109012991 0.0630536675]
[0.344495356 0.134818345 0.0964551568]
[0.115377188]
[0.294055104 0.213707566 0.135266036]
FastEstimator-ModelSaver: Saving model to /data/hsiming/mscoco_model/retinanet_best_total_loss.h5
FastEstimator-Eval: step: 630; epoch: 104; focal_loss: 1.1072116; l1_loss: 0.3089; total_loss: 1.4161114; 
FastEstimator-Train: step: 630; focal_loss: 0.0020336; l1_loss: 0.0357883; total_loss: 0.0378219; examples/sec: 31.7; progress: 52.5%; 
FastEstimator-Train: step: 631; focal_loss: 0.0061269; l1_loss: 0.0175403; total_loss: 0.0236672; examples/sec: 32.0; progress: 52.6%; 
FastEstimator-Train: step: 632; focal_loss: 0.0049022; l1_loss: 0.0150664; total_loss: 0.0199686; examples/sec: 32.1; 

FastEstimator-Train: step: 642; focal_loss: 0.0028142; l1_loss: 0.0319822; total_loss: 0.0347964; examples/sec: 32.0; progress: 53.5%; 
FastEstimator-Train: step: 643; focal_loss: 0.1317086; l1_loss: 0.0299961; total_loss: 0.1617047; examples/sec: 32.1; progress: 53.6%; 
FastEstimator-Train: step: 644; focal_loss: 0.0093102; l1_loss: 0.021568; total_loss: 0.0308782; examples/sec: 32.2; progress: 53.7%; 
FastEstimator-Train: step: 645; focal_loss: 0.0062364; l1_loss: 0.0252624; total_loss: 0.0314988; examples/sec: 32.3; progress: 53.8%; 
FastEstimator-Train: step: 646; focal_loss: 0.0185435; l1_loss: 0.0391285; total_loss: 0.057672; examples/sec: 31.7; progress: 53.8%; 
FastEstimator-Train: step: 647; focal_loss: 0.134482; l1_loss: 0.0371989; total_loss: 0.1716809; examples/sec: 31.6; progress: 53.9%; 
[0.604662836 0.124921888 0.109268695 ... 0.0625639856 0.0619937479 0.052852571]
[0.48747468 0.190838814 0.162356794 0.0664755106 0.0574393272 0.0531960428]
[0.176826537]
[0.44397071 0.331

FastEstimator-Train: step: 657; focal_loss: 0.0070171; l1_loss: 0.0309625; total_loss: 0.0379796; examples/sec: 32.2; progress: 54.8%; 
FastEstimator-Train: step: 658; focal_loss: 0.1478654; l1_loss: 0.0221709; total_loss: 0.1700362; examples/sec: 31.7; progress: 54.8%; 
FastEstimator-Train: step: 659; focal_loss: 0.1013836; l1_loss: 0.0338636; total_loss: 0.1352472; examples/sec: 32.3; progress: 54.9%; 
[0.357995808]
[0.220165908 0.0902354419 0.0728203654 0.0567463934 0.0560470521]
[0.500548124 0.465141207 0.423995018 ... 0.0548717678 0.051266104 0.0507295728]
[0.353452802 0.273236454 0.248072982 ... 0.0539931953 0.0523068309 0.0504642427]
[0.115032852 0.0977292955 0.0892079473 ... 0.0579850078 0.0543335676 0.0532668233]
[0.523044586 0.19891122 0.119070858 ... 0.0849818 0.057290554 0.0571349561]
[0.158453375]
[0.395943969 0.288360655 0.198517501 0.0528742075]
[0.918490171 0.410430759 0.32435149 ... 0.0839189887 0.0818698704 0.0556947]
[0.439076781 0.241383374 0.23472774 ... 0.05303707

FastEstimator-Train: step: 669; focal_loss: 0.1795622; l1_loss: 0.0430481; total_loss: 0.2226103; examples/sec: 32.1; progress: 55.8%; 
FastEstimator-Train: step: 670; focal_loss: 0.3504708; l1_loss: 0.0494707; total_loss: 0.3999415; examples/sec: 32.3; progress: 55.8%; 
FastEstimator-Train: step: 671; focal_loss: 0.0630338; l1_loss: 0.0469104; total_loss: 0.1099442; examples/sec: 32.2; progress: 55.9%; 
[0.665555537 0.495239645 0.190000892 ... 0.0526860058 0.0513363183 0.0508416]
[0.597489417]
[0.302581102 0.296740711 0.283842802 ... 0.0514186323 0.0512779355 0.0507778227]
[0.514990747 0.357604325 0.315797031 ... 0.0624733269 0.0578773618 0.0529994369]
[0.440436602 0.0784002841]
[0.282199919 0.276283026 0.164988637 ... 0.0631274879 0.0624605417 0.0602733493]
[0.429455549 0.375192702 0.313664734 ... 0.0539202094 0.0527746081 0.0506733358]
[0.670324683 0.620925 0.402837902 ... 0.0513035059 0.0507264733 0.0507079363]
[0.293321669 0.273479551 0.224496782 ... 0.0554335713 0.0539876819 0.05

[0.178957254 0.157964438 0.152145118 ... 0.053682059 0.0513151586 0.0503518283]
[0.668167293 0.573023677 0.448783427 ... 0.0565038025 0.0555054247 0.0548448563]
FastEstimator-ModelSaver: Saving model to /data/hsiming/mscoco_model/retinanet_best_total_loss.h5
FastEstimator-Eval: step: 678; epoch: 112; focal_loss: 0.4312356; l1_loss: 0.1728827; total_loss: 0.6041182; 
FastEstimator-Train: step: 678; focal_loss: 0.1905103; l1_loss: 0.0224558; total_loss: 0.2129661; examples/sec: 32.3; progress: 56.5%; 
FastEstimator-Train: step: 679; focal_loss: 0.0600124; l1_loss: 0.0268528; total_loss: 0.0868652; examples/sec: 32.4; progress: 56.6%; 
FastEstimator-Train: step: 680; focal_loss: 0.1739495; l1_loss: 0.0375581; total_loss: 0.2115076; examples/sec: 32.2; progress: 56.7%; 
FastEstimator-Train: step: 681; focal_loss: 0.0755624; l1_loss: 0.0533691; total_loss: 0.1289315; examples/sec: 32.3; progress: 56.8%; 
FastEstimator-Train: step: 682; focal_loss: 0.0422541; l1_loss: 0.0195261; total_loss: 

[0.721422672 0.0694773793 0.0670466125 ... 0.060680747 0.0570817292 0.056370616]
[0.564496517 0.466301829 0.158254862 0.0657308102 0.0534073412]
[0.773056388 0.501619101 0.480591863 ... 0.0520426333 0.0519253314 0.0502451062]
[0.207465321 0.106231689 0.101066202 ... 0.0711268187 0.0609183311 0.0500826836]
[0.452251017 0.414142817 0.265720844 ... 0.0514279 0.0509253442 0.050886631]
[0.487859368 0.396845281 0.285999417 ... 0.0528683662 0.0521899462 0.0502327383]
[0.83436209 0.810677171 0.804888964 ... 0.0819424093 0.0717371702 0.0506022871]
[0.178875595 0.177881718 0.175676286 0.137518495 0.0890050232 0.0655146539]
[0.638229609 0.637545705 0.525219381 ... 0.0800782144 0.0799779892 0.079949975]
[0.419492126 0.306917548 0.294177622 ... 0.0685270429 0.06278494 0.0538773239]
[0.314388245 0.294000268 0.198050797 ... 0.0506145656 0.0501817763 0.050098896]
[0.406025231 0.243697941 0.219046324 ... 0.0527008772 0.0520302057 0.050506413]
[0.673157752 0.5148049 0.475925237 ... 0.0921224952 0.091140

[0.131379485 0.05545789]
[0.211716086 0.206838369 0.13239333 ... 0.0801693201 0.0775903463 0.0522659123]
[0.970142543 0.692684114 0.666538656 ... 0.0605958104 0.0547152758 0.0524018407]
[0.878739 0.677323 0.387910753 ... 0.051243186 0.0511514544 0.0500181913]
[0.30691871 0.216824532 0.0955790877 ... 0.0576221943 0.057264 0.0548370183]
[0.4799532 0.394361526 0.368334055 ... 0.0511380732 0.0510174334 0.0508728921]
[0.688984454 0.298311 0.141096264 ... 0.0601581931 0.0571522117 0.0559647679]
[0.983113289 0.214941829 0.130921781 ... 0.0619567037 0.0617144108 0.0603604615]
[0.709441 0.684812307 0.365926206 ... 0.0582359135 0.0541982353 0.0512341857]
[0.742283106 0.664919376 0.653376937 ... 0.0516348779 0.0508626103 0.0508121252]
[0.604221046 0.562787771 0.539108 ... 0.0531536937 0.0521126688 0.0513457358]
[0.700054288 0.619919121 0.603332281 ... 0.0708183348 0.0702505112 0.0539055169]
[0.494437933 0.37810573 0.265744567 ... 0.0567864776 0.0558066964 0.0554018915]
[0.838605285 0.824834228 0.

[0.858209312 0.3948614 0.356950879 ... 0.0574390888 0.0530320406 0.0510483682]
[0.722614765 0.574226439 0.431065947 ... 0.054058224 0.0528491735 0.0507943928]
[0.8439188 0.610156357 0.591733813 ... 0.0588915646 0.0565278232 0.0537016392]
[0.435533881 0.295226514 0.246734172 ... 0.0632313788 0.0551922321 0.0535755455]
[0.5701316 0.497209817 0.329361379 ... 0.0599584281 0.0571017265 0.0562036633]
[0.52953 0.0637444258]
[0.67930603 0.560824931 0.497792482 ... 0.0521716475 0.0514104068 0.0513552427]
[0.811264157 0.701962948 0.480892181 ... 0.0529607832 0.0514843464 0.0504640043]
[0.904707074 0.0617035329]
[0.413131773 0.409342438 0.253623903 ... 0.0541245341 0.0530185401 0.0508090556]
[0.499198556 0.433604598 0.413340598 ... 0.0544272661 0.0533145368 0.0507461429]
[0.935588896 0.701475143 0.648777843 ... 0.0514777601 0.0513827801 0.0508265793]
[0.649469733 0.545588 0.520842373 ... 0.0511163175 0.0509785116 0.0500276089]
[0.504907429 0.347852975 0.289457768 ... 0.0533477664 0.0532406867 0.0

[0.593682647 0.572064281 0.492720753 ... 0.0521681607 0.0503281951 0.0501169264]
[0.833694816 0.605012715 0.329923272 ... 0.0550515056 0.0517785549 0.0508556366]
[0.694702268 0.603718042 0.469261944 ... 0.061676681 0.0567061 0.0563017726]
[0.68360877 0.550111294 0.479891181 ... 0.0608949661 0.0604490936 0.0602273345]
[0.954952717 0.951741695 0.836497903 ... 0.0522738695 0.0519091487 0.0508750379]
[0.447771072 0.339779109 0.241602629 ... 0.0539602935 0.052598 0.0520339608]
[0.465078801 0.405547142 0.350104392 ... 0.0667699 0.0546488166 0.0533756316]
[0.535529375 0.402446806 0.358587384 ... 0.0514341295 0.0507186651 0.0504982471]
[0.927237749 0.58871007 0.356284261 ... 0.0659426153 0.0637661815 0.0548972189]
[0.827127039 0.740852177 0.724236965 ... 0.0561836362 0.0520267785 0.0511915684]
[0.421040535 0.408052832 0.067066133 0.0612618029]
[0.557431281 0.519748092 0.486033738 ... 0.0639822781 0.0636205673 0.0515404642]
[0.857348204 0.705157042 0.701877356 ... 0.0567397773 0.0540021062 0.05

FastEstimator-Train: step: 732; focal_loss: 0.0551408; l1_loss: 0.0403481; total_loss: 0.0954889; examples/sec: 32.0; progress: 61.0%; 
FastEstimator-Train: step: 733; focal_loss: 0.1367015; l1_loss: 0.0646685; total_loss: 0.20137; examples/sec: 32.1; progress: 61.1%; 
FastEstimator-Train: step: 734; focal_loss: 0.0554771; l1_loss: 0.1249119; total_loss: 0.180389; examples/sec: 32.4; progress: 61.2%; 
FastEstimator-Train: step: 735; focal_loss: 0.11505; l1_loss: 0.062174; total_loss: 0.1772239; examples/sec: 32.5; progress: 61.3%; 
FastEstimator-Train: step: 736; focal_loss: 0.1658781; l1_loss: 0.0418784; total_loss: 0.2077566; examples/sec: 32.2; progress: 61.3%; 
FastEstimator-Train: step: 737; focal_loss: 0.0776027; l1_loss: 0.0408695; total_loss: 0.1184723; examples/sec: 32.3; progress: 61.4%; 
[0.955985665 0.248498768 0.159327239 ... 0.0537985861 0.0529943705 0.0516405702]
[0.945326388 0.928913474 0.158995122 0.133602232 0.0778353512 0.0699996054]
[0.617554605 0.59001112 0.5788986

[0.719384193 0.458798 0.388058752 ... 0.0514713228 0.0505156219 0.0502729714]
[0.926237881 0.287954718 0.20689249 ... 0.0950660408 0.0852174163 0.0693394542]
[0.644742727 0.514855325 0.506853163 ... 0.0540053546 0.0537928343 0.0529681444]
[0.321601361 0.277148038 0.0694525838 ... 0.0537130535 0.053635627 0.0526194274]
[0.587916851 0.317831784 0.0926033854 0.0609043241]
[0.41032818 0.347215414 0.236393839 ... 0.0554153621 0.0532570779 0.0510716438]
[0.833414257 0.799075961 0.67195797 ... 0.0513311028 0.0510555804 0.0507684052]
[0.578912377 0.544010162 0.49088341 ... 0.0545815527 0.0545344949 0.0501659811]
[0.64137584 0.634209633 0.621195614 ... 0.054564178 0.0543952584 0.0521586835]
[0.515253723 0.51384145 0.353633106 ... 0.063267529 0.058737427 0.0517099798]
[0.694915712 0.655280232 0.62871331 ... 0.0525591373 0.051379174 0.0502901673]
FastEstimator-Eval: step: 744; epoch: 123; focal_loss: 0.2699861; l1_loss: 0.1631771; total_loss: 0.4331632; 
FastEstimator-Train: step: 744; focal_loss

[0.688577414 0.664024115 0.656349719 ... 0.0538744926 0.0537202954 0.0533328354]
[0.967129588 0.644726038 0.638837576 ... 0.065620482 0.0594682097 0.0555567741]
[0.835100114 0.822604537 0.758526564 ... 0.0521203578 0.050886184 0.0500023663]
[0.482033491 0.355016 0.323306352 ... 0.052485317 0.0518018 0.0503425896]
[0.659902811 0.394383729 0.162163615 ... 0.0651066 0.0552196801 0.0537543]
[0.753707886 0.583289146 0.502159238 ... 0.059271574 0.0578190088 0.0577769578]
[0.540013134 0.0794286728]
[0.674817383 0.663378716 0.643914878 ... 0.0518387258 0.0517554879 0.0509762764]
[0.642773509 0.363275677 0.333077252 ... 0.0599576235 0.0536765158 0.0518066585]
[0.629090667 0.0583052337]
[0.647925377 0.375527561 0.222218215 ... 0.0629496 0.057686 0.0520711243]
[0.742174327 0.533685923 0.511916757 ... 0.0558618903 0.054897517 0.0525180399]
[0.803314865 0.684446335 0.63384217 ... 0.0513674617 0.0506644249 0.0504499376]
[0.646474063 0.492065489 0.452304751 ... 0.0527798831 0.0513765216 0.0511850417]

[0.437681973 0.369197905 0.0517551601]
[0.769713759 0.705910563 0.565941095 ... 0.0530162454 0.0514056087 0.0500372052]
[0.903800666 0.873859525 0.85802114 ... 0.0560629368 0.0509468019 0.0507828295]
[0.915516198 0.847102523 0.702217162 ... 0.0651109219 0.0610534251 0.0567607582]
[0.618682444 0.61279732 0.486691773 0.456743658 0.342828691]
[0.819221377 0.725393176 0.569992065 ... 0.0834411383 0.0834227204 0.0807135105]
[0.964934349 0.936828792 0.903760076 ... 0.072075516 0.0585316718 0.0500297844]
[0.769546 0.75211072 0.523225486 ... 0.0541628 0.0535402 0.0516880453]
[0.857213855 0.734767556 0.501986742 ... 0.0604943037 0.0553568304 0.052354902]
[0.711224675 0.693070829 0.658426583 ... 0.0678683221 0.0675451159 0.0675177574]
[0.573623478 0.418025792 0.0688147843 0.0633159]
[0.831242919 0.684972644 0.620907962 ... 0.0581001639 0.0563703179 0.0530548394]
[0.461241186 0.439186484 0.178498119]
[0.701743484 0.550097942 0.54074508 ... 0.051247 0.0505506694 0.050532341]
[0.680594862 0.5775187

[0.908306718 0.876688123 0.870435238 ... 0.0506021976 0.0504875779 0.050450176]
[0.784340382 0.771710038 0.732365966 ... 0.0512571037 0.0503064394 0.0500558317]
[0.877761722 0.875578821 0.86428 ... 0.0599367917 0.0544269085 0.0543575883]
[0.836075664 0.712650478 0.699574709 ... 0.0552592278 0.051902324 0.0500296652]
[0.983996511 0.948947906 0.92110759 ... 0.0528155565 0.0511754751 0.0503784716]
[0.935886681 0.90455544 0.848786116 ... 0.0517741144 0.0507949293 0.0507785678]
[0.950003326 0.788076758 0.0759184062 0.0562564433]
[0.946236 0.909918785 0.874352872 ... 0.0525333285 0.0513377488 0.0508122444]
[0.820026934 0.730148494 0.719498336 ... 0.0545840263 0.0511951745 0.0500143766]
[0.929778814 0.0902944207 0.0531881452]
[0.853752732 0.400241256 0.0722846091]
[0.949653268 0.920603752 0.847258 ... 0.0540286899 0.0522843 0.0507109165]
[0.598818481 0.520620465 0.0866089761 ... 0.0592666268 0.0585159957 0.0567590594]
[0.789516866 0.776664495 0.711874545 ... 0.0525068939 0.0515041053 0.051007

FastEstimator-Train: step: 789; focal_loss: 0.0082821; l1_loss: 0.0323703; total_loss: 0.0406523; examples/sec: 32.1; progress: 65.8%; 
FastEstimator-Train: step: 790; focal_loss: 0.0087263; l1_loss: 0.0504311; total_loss: 0.0591574; examples/sec: 32.2; progress: 65.8%; 
FastEstimator-Train: step: 791; focal_loss: 0.007581; l1_loss: 0.0210832; total_loss: 0.0286642; examples/sec: 32.2; progress: 65.9%; 
[0.957128763 0.0679484606 0.0594261 0.0527543724]
[0.752131581 0.649321 0.602181196 0.0785408616 0.0738808215 0.0573323667]
[0.96915555 0.820820451 0.796492457 ... 0.0580756068 0.0555752814 0.0511514544]
[0.961515188 0.909127176 0.847352862 ... 0.0542191565 0.0541686416 0.0541475415]
[0.907665253 0.447690427 0.423105121 ... 0.0636073053 0.057685703 0.0523092747]
[0.955648541 0.700032175 0.677431047 ... 0.0574179292 0.0546875298 0.0544997752]
[0.763437867 0.760058 0.666823864 ... 0.0538520515 0.0517547429 0.0512881279]
[0.934389234 0.434296 0.112941206 0.0595384836 0.0555502474]
[0.98035

FastEstimator-Train: step: 798; focal_loss: 0.0035538; l1_loss: 0.0269338; total_loss: 0.0304876; examples/sec: 32.1; progress: 66.5%; 
FastEstimator-Train: step: 799; focal_loss: 0.002255; l1_loss: 0.0252261; total_loss: 0.0274811; examples/sec: 32.2; progress: 66.6%; 
FastEstimator-Train: step: 800; focal_loss: 0.0041577; l1_loss: 0.0249243; total_loss: 0.029082; examples/sec: 32.1; progress: 66.7%; 
FastEstimator-Train: step: 801; focal_loss: 0.0074484; l1_loss: 0.0678288; total_loss: 0.0752772; examples/sec: 32.3; progress: 66.8%; 
FastEstimator-Train: step: 802; focal_loss: 0.0033682; l1_loss: 0.074268; total_loss: 0.0776362; examples/sec: 32.3; progress: 66.8%; 
FastEstimator-Train: step: 803; focal_loss: 0.0073864; l1_loss: 0.0445856; total_loss: 0.051972; examples/sec: 32.0; progress: 66.9%; 
[0.898854911 0.857657254 0.812520504 ... 0.0518444479 0.0506154895 0.0503623784]
[0.898656726 0.838658571 0.798720241 ... 0.0536016226 0.0513634682 0.0507010221]
[0.928447962 0.761899114 0

FastEstimator-Train: step: 810; focal_loss: 0.0038973; l1_loss: 0.0425238; total_loss: 0.0464211; examples/sec: 32.0; progress: 67.5%; 
FastEstimator-Train: step: 811; focal_loss: 0.0014403; l1_loss: 0.0460901; total_loss: 0.0475303; examples/sec: 32.3; progress: 67.6%; 
FastEstimator-Train: step: 812; focal_loss: 0.0048634; l1_loss: 0.0263232; total_loss: 0.0311866; examples/sec: 32.1; progress: 67.7%; 
FastEstimator-Train: step: 813; focal_loss: 0.0052426; l1_loss: 0.0215707; total_loss: 0.0268132; examples/sec: 31.7; progress: 67.8%; 
FastEstimator-Train: step: 814; focal_loss: 0.0028361; l1_loss: 0.0431941; total_loss: 0.0460302; examples/sec: 31.6; progress: 67.8%; 
FastEstimator-Train: step: 815; focal_loss: 0.0022976; l1_loss: 0.0443682; total_loss: 0.0466659; examples/sec: 32.1; progress: 67.9%; 
[0.870610356 0.801984072 0.786675096 ... 0.0501703918 0.0500993729 0.050011754]
[0.914631844 0.707089543 0.686568499 ... 0.0602876544 0.0535699129 0.0510770679]
[0.878510714]
[0.997774

FastEstimator-Train: step: 822; focal_loss: 0.0017645; l1_loss: 0.0286269; total_loss: 0.0303914; examples/sec: 32.2; progress: 68.5%; 
FastEstimator-Train: step: 823; focal_loss: 0.0034753; l1_loss: 0.0420045; total_loss: 0.0454798; examples/sec: 32.6; progress: 68.6%; 
FastEstimator-Train: step: 824; focal_loss: 0.0013789; l1_loss: 0.0340077; total_loss: 0.0353866; examples/sec: 32.1; progress: 68.7%; 
FastEstimator-Train: step: 825; focal_loss: 0.0018059; l1_loss: 0.0182239; total_loss: 0.0200298; examples/sec: 32.3; progress: 68.8%; 
FastEstimator-Train: step: 826; focal_loss: 0.0026228; l1_loss: 0.0529361; total_loss: 0.0555589; examples/sec: 32.0; progress: 68.8%; 
FastEstimator-Train: step: 827; focal_loss: 0.0014477; l1_loss: 0.0365591; total_loss: 0.0380068; examples/sec: 31.9; progress: 68.9%; 
[0.879352 0.874007642 0.856362939 ... 0.0589324832 0.0568523109 0.0522651672]
[0.910331428 0.669420838 0.288983107 0.0501722395]
[0.860603929 0.835634828 0.784956217 ... 0.0646173656 0

FastEstimator-Train: step: 836; focal_loss: 0.0011162; l1_loss: 0.0404308; total_loss: 0.041547; examples/sec: 32.2; progress: 69.7%; 
FastEstimator-Train: step: 837; focal_loss: 0.001691; l1_loss: 0.036279; total_loss: 0.0379699; examples/sec: 32.2; progress: 69.8%; 
FastEstimator-Train: step: 838; focal_loss: 0.0007753; l1_loss: 0.0583227; total_loss: 0.059098; examples/sec: 31.7; progress: 69.8%; 
FastEstimator-Train: step: 839; focal_loss: 0.0007995; l1_loss: 0.0610665; total_loss: 0.061866; examples/sec: 31.7; progress: 69.9%; 
[0.797545314 0.691628754 0.654227138 ... 0.0537872314 0.0516819358 0.0500812531]
[0.927046061 0.860946298 0.860409379 ... 0.061542213 0.0598086715 0.0520520508]
[0.966795325 0.941554666 0.865298271 ... 0.0577817857 0.0544731915 0.0521793365]
[0.933338583 0.914041758 0.8358531 ... 0.059900254 0.0566075146 0.0550605059]
[0.908043563 0.903879166 0.901364803 ... 0.0597094 0.0587637424 0.0518798232]
[0.925958037 0.706524789 0.286892295 0.0668620765]
[0.899970114

FastEstimator-Train: step: 849; focal_loss: 0.0008533; l1_loss: 0.0347343; total_loss: 0.0355876; examples/sec: 32.2; progress: 70.8%; 
FastEstimator-Train: step: 850; focal_loss: 0.0013265; l1_loss: 0.0183581; total_loss: 0.0196847; examples/sec: 32.2; progress: 70.8%; 
FastEstimator-Train: step: 851; focal_loss: 0.0030012; l1_loss: 0.0210178; total_loss: 0.0240191; examples/sec: 32.1; progress: 70.9%; 
[0.979982615 0.972171128 0.968289495 ... 0.0509839058 0.0508106351 0.0500619709]
[0.83627516 0.698421717 0.0596551 0.0523320138]
[0.965890527 0.934509277 0.900572658 ... 0.0594161153 0.0558886826 0.0529549718]
[0.904986262 0.880728126 0.717078805]
[0.835329294 0.72068435 0.719867587 ... 0.0577878952 0.0527943373 0.0523260534]
[0.942605495 0.887712479 0.876561522 ... 0.0629632473 0.0581015348 0.0536645055]
[0.970537901 0.937955737 0.854250133 ... 0.149129659 0.118032753 0.0501561463]
[0.950315893 0.937846541 0.8874439 ... 0.0521388054 0.0513887703 0.0502964556]
[0.887974262 0.88322109 0

FastEstimator-Train: step: 862; focal_loss: 0.0018637; l1_loss: 0.0407947; total_loss: 0.0426584; examples/sec: 32.0; progress: 71.8%; 
FastEstimator-Train: step: 863; focal_loss: 0.0009118; l1_loss: 0.0208697; total_loss: 0.0217816; examples/sec: 32.1; progress: 71.9%; 
[0.988226235 0.979676485 0.942842841 ... 0.063388288 0.0627319813 0.0616832078]
[0.986588597 0.951426744 0.921721041 0.911263108 0.0762671232 0.0572445095]
[0.969943404 0.965094328 0.809645176 ... 0.0610096157 0.0522919297 0.0521710813]
[0.928738534 0.910721242 0.857566655 ... 0.0604988337 0.0525117517 0.0505128801]
[0.980156481 0.964541912 0.963017344 ... 0.050863117 0.0506315827 0.0504248142]
[0.901982486 0.791793823 0.0658608079 0.0542175472]
[0.968123674 0.93746686 0.91489768 ... 0.0575587451 0.0554938 0.0514782071]
[0.93000412 0.901458 0.763736367]
[0.863455534 0.771876574 0.757409096 ... 0.0594409108 0.053013891 0.0529858768]
[0.939145 0.906911969 0.887225807 ... 0.0642320514 0.0615943372 0.0555223525]
[0.9717507

FastEstimator-Train: step: 875; focal_loss: 0.0005565; l1_loss: 0.0216857; total_loss: 0.0222422; examples/sec: 31.9; progress: 72.9%; 
[0.940528631 0.918619454 0.917161226 ... 0.0563088655 0.0510513484 0.0502783954]
[0.970626235 0.918814838 0.899016201 ... 0.0966052115 0.0768665373 0.0523972213]
[0.989470601 0.982217789 0.886840165 0.865125418 0.782918692 0.0613679588]
[0.862078905 0.861681104 0.801786602 0.796282947 0.757941246]
[0.987024486 0.980204582 0.941722631 ... 0.0601262748 0.0598073 0.0579756796]
[0.987735271 0.939078391 0.914279699 0.908046246 0.0746070743 0.0578594804]
[0.97851 0.971387506 0.815289617 ... 0.064363122 0.0623963773 0.0511934757]
[0.942163408 0.914179444 0.883928418 ... 0.0654030144 0.0530032516 0.0516548753]
[0.982181191 0.973061919 0.969640255 ... 0.0508372486 0.0507825911 0.0503291786]
[0.901428 0.803266287 0.0606952608 0.051209718]
[0.970137656 0.946533084 0.91647017 ... 0.0627652109 0.0536979437 0.0525535345]
[0.942878366 0.913023949 0.796125174]
[0.8468

[0.96040535 0.902467]
[0.988695383 0.962635279 0.956064224 ... 0.0566265 0.051807344 0.0516478717]
[0.860649586 0.849151134]
[0.96236527 0.944600701 0.944356918 ... 0.0541586578 0.0526125431 0.0523253679]
[0.973619938 0.921426535 0.91575 ... 0.114045888 0.0520474315 0.051722914]
[0.988221645 0.979706526 0.881405592 0.876795053 0.806850791 0.0568434894]
[0.849513292 0.834024668 0.81482023 0.777703047 0.766858459]
[0.993812144 0.982426584 0.960620642 ... 0.0724314451 0.0707576 0.0707142651]
[0.993204 0.950639725 0.94633019 0.929328561 0.0798342526 0.0679717958]
[0.985421717 0.984297514 0.860358477 ... 0.0631547 0.0547643 0.0514837801]
[0.947953343 0.915977 0.896204233 0.859866619 0.0519766808]
[0.989653289 0.986101329 0.978489041 ... 0.0517760515 0.051666528 0.0509934723]
[0.906697392 0.841789961 0.0696144402 0.0530832708]
[0.98140192 0.956484437 0.933813155 ... 0.0600841343 0.0532211661 0.051420778]
[0.918244958 0.885816276 0.823516846]
[0.916996717 0.8319695 0.817633927 ... 0.056119859

[0.974216759]
[0.953282475 0.873267889]
[0.984329164 0.969413579 0.952729464 ... 0.0639014542 0.0520906746 0.0514981151]
[0.83167243 0.777287304]
[0.958627582 0.942722797 0.941391945 ... 0.0574969947 0.0563043356 0.0560064316]
[0.972395301 0.921062827 0.912425816 ... 0.262530506 0.0800351202 0.0690264404]
[0.983410597 0.971685529 0.886279583 0.844846845 0.811576128]
[0.83698976 0.802505732 0.795507789 0.79308331 0.718308806]
[0.994649053 0.9837116 0.962363243 ... 0.0554858744 0.054491967 0.0542697906]
[0.983044 0.906983733 0.880253673 0.841587067 0.0630940199 0.0573455393]
[0.987634897 0.985719323 0.849816501 ... 0.0575243533 0.0547577739 0.0509500504]
[0.952017903 0.932458401 0.905144274 0.880702376 0.0660816431 0.0575920343]
[0.989687085 0.987596273 0.982499182 ... 0.0519664288 0.050960362 0.0502238572]
[0.870270371 0.767701566]
[0.974037051 0.954182386 0.924227357 ... 0.0555329621 0.0535712838 0.0515583754]
[0.942373 0.908268452 0.861322522]
[0.891737461 0.807399571 0.801724553 ... 

[0.93921572 0.929042459 0.916933894 ... 0.063839823 0.0540422499 0.0520345271]
[0.968748212]
[0.965303898 0.908185482]
[0.990685284 0.973594666 0.968287468 ... 0.0716958344 0.0628718734 0.0513574481]
[0.90646708 0.882569909]
[0.968536615 0.954532564 0.947164297 ... 0.0627558529 0.0581674874 0.0564645529]
[0.97164917 0.918342 0.917755842 ... 0.271827906 0.104556233 0.0703784227]
[0.992759526 0.985837579 0.914718866 0.903414786 0.8412]
[0.882458 0.879746914 0.874957681 0.837980628 0.826498747]
[0.994650841 0.987159371 0.964103103 ... 0.0689727068 0.0686681867 0.0683665276]
[0.986402512 0.919077158 0.9162817 0.889813185 0.0686297715 0.0579316914]
[0.99042809 0.989152133 0.896249413 ... 0.0657588243 0.0640679896 0.0581184328]
[0.959008336 0.933353424 0.913450956 0.91016382 0.0692138672]
[0.991342664 0.989661515 0.983756304 ... 0.0509416163 0.0505082309 0.0500374436]
[0.923262835 0.887289762 0.0593176484 0.0528619289]
[0.9799335 0.961394787 0.947336793 ... 0.0587359071 0.0521206558 0.050048

[0.982706904]
[0.970320165 0.91313]
[0.986598134 0.969181776 0.968540549 ... 0.0684419572 0.0585094094 0.0575584471]
[0.893200815 0.881037772]
[0.959422112 0.947104 0.932830215 ... 0.0584973693 0.053303808 0.0516652763]
[0.97731328 0.924516201 0.912564754 ... 0.314264238 0.0948779 0.0524593294]
[0.985141337 0.974673808 0.903345525 0.843259573 0.842518 0.0525993705]
[0.87249589 0.867417276 0.866572738 0.814622283 0.811412573]
[0.995847344 0.983018041 0.973513722 ... 0.059833914 0.0596835613 0.0581290722]
[0.991942286 0.946393132 0.935236216 0.924261093 0.0522845089]
[0.988976717 0.988500118 0.877146721 ... 0.074760288 0.0678450167 0.055328697]
[0.951635301 0.943366051 0.923526943 0.91792357 0.066852]
[0.991507351 0.989513755 0.987754345 ... 0.0517450273 0.0517393351 0.0512526333]
[0.876730561 0.839425921]
[0.980628967 0.966766238 0.938717604 ... 0.0599773228 0.0520034134 0.0516348779]
[0.94787997 0.907974243 0.853567123]
[0.908908 0.866111279 0.851853967 ... 0.0581329763 0.0526091456 0.

[0.816430211 0.765811086]
[0.964180231 0.961146235 0.942639709 ... 0.0535874069 0.05302 0.0517349839]
[0.976660609 0.93137145 0.90653193 ... 0.433971047 0.344106734 0.0759563148]
[0.978521466 0.968624711 0.900921941 0.853558183 0.853194]
[0.820752263 0.812842369 0.808144689 0.786672235 0.729143143]
[0.996460617 0.986513197 0.978723884 ... 0.0612683 0.060963124 0.0595947802]
[0.992846131 0.9399966 0.917860508 0.913852 0.0840957761]
[0.989554644 0.988038898 0.895920873 ... 0.0691849 0.0626558661 0.0541936457]
[0.960595369 0.949829102 0.935446262 0.900075614 0.0644493401]
[0.993511319 0.992420733 0.989019752 ... 0.053196311 0.0512495637 0.0505553782]
[0.876845241 0.799962759]
[0.977295101 0.961348772 0.940017104 ... 0.0627031326 0.0609891415 0.0544193685]
[0.93514967 0.888810158 0.860485137]
[0.918018341 0.867808759 0.86435163 ... 0.0721326768 0.0591856837 0.0507456064]
[0.955173314 0.946622729 0.900416493 ... 0.0570127368 0.0520332456 0.050033927]
[0.979360104 0.944316 0.880553484 ... 0.

[0.980029345 0.949716 0.919297218 ... 0.449196786 0.396700591 0.0773110688]
[0.97876358 0.972199917 0.90846777 0.867001295 0.861978769]
[0.891652 0.872557402 0.869345427 0.849787 0.847208261]
[0.997444093 0.986020803 0.970826149 ... 0.0599572957 0.0594287813 0.058716923]
[0.992760718 0.943412423 0.907202899 0.8962304 0.0908973813]
[0.992568374 0.991239667 0.891717672 ... 0.066228 0.0647281408 0.0540353954]
[0.940707147 0.937490821 0.922140658 0.858680606 0.0687733293 0.055297792]
[0.995448351 0.993905783 0.99190259 ... 0.0504125953 0.0502918959 0.0501615703]
[0.891245604 0.818029881]
[0.975187182 0.957164645 0.937841654 ... 0.0711938739 0.0571653545 0.0505075157]
[0.896031797 0.828553438 0.820901394]
[0.9232 0.875717163 0.871485233 ... 0.155656844 0.0583992898 0.0572593212]
[0.95199883 0.951859236 0.916822195 ... 0.0636319518 0.0611003935 0.0566411316]
[0.972578526 0.929459 0.872691274 ... 0.771763921 0.111585796 0.106024534]
[0.990640461 0.981754 0.97166121 ... 0.0525617599 0.05147248

[0.937135816 0.932798445 0.931853771 0.908491373 0.907819092]
[0.997946918 0.989834428 0.987761617 ... 0.0614237189 0.0567100644 0.0565746129]
[0.993097782 0.946521521 0.932652771 0.9314906 0.0721493363]
[0.991121888 0.990930319 0.920196235 ... 0.0742862225 0.0664850771 0.0644314]
[0.950694442 0.947881222 0.927879 0.877893567 0.0538193882 0.0513020158]
[0.995110035 0.994844198 0.992538154 ... 0.0517925918 0.0513912737 0.0510068238]
[0.920451283 0.856397212 0.0512179434]
[0.981122077 0.973933697 0.947257757 ... 0.0577824116 0.0551607907 0.0500663221]
[0.890592456 0.821444631 0.820183277]
[0.938385844 0.90528667 0.887911558 ... 0.0679930747 0.0608599782 0.0539661944]
[0.96161747 0.94772613 0.943173528 ... 0.0637236834 0.0609933436 0.0530236065]
[0.97603178 0.942931414 0.886331916 ... 0.114480346 0.107264489 0.0828826427]
[0.989503145 0.9827407 0.973493218 ... 0.0524298549 0.0505481958 0.0504063666]
[0.946013 0.933565259 0.931873858 ... 0.09673208 0.0574520528 0.0564605]
[0.972046375 0.83

[0.996904135 0.960899949 0.95716095 0.942347527]
[0.993842244 0.993228436 0.937894702 ... 0.0517613 0.0503233075 0.050265789]
[0.973918378 0.959869146 0.937526226 0.898635745 0.0592221618]
[0.997356653 0.994035304 0.992372572 ... 0.0512903631 0.0506452918 0.0503663123]
[0.940405488 0.86832428]
[0.982095838 0.981964707 0.960575 ... 0.0572196543 0.0542551577 0.0510094166]
[0.862799108 0.827291965 0.808608055]
[0.951067626 0.92469275 0.917409062 ... 0.060944885 0.0555166602 0.0516949892]
[0.950114489 0.938418925 0.936762452 ... 0.0778161883 0.0612257421 0.0536166728]
[0.992162466 0.978321075 0.936132133 ... 0.895850301 0.16355744 0.153845042]
[0.993904829 0.987887621 0.979735672 ... 0.0555112064 0.054056406 0.052546382]
FastEstimator-Eval: step: 972; epoch: 161; focal_loss: 0.0008599; l1_loss: 0.0647693; total_loss: 0.0656292; 
FastEstimator-Train: step: 972; focal_loss: 0.000311; l1_loss: 0.0500548; total_loss: 0.0503658; examples/sec: 32.4; progress: 81.0%; 
FastEstimator-Train: step: 9

[0.971312523 0.947927833 0.932774484 0.910289049 0.058888495]
[0.997984648 0.995246291 0.994708061 ... 0.0514047742 0.0507008731 0.0500239432]
[0.94590044 0.895130038 0.0513501465]
[0.990263939 0.984804869 0.967282593 ... 0.05978477 0.0590226054 0.0553343892]
[0.905868649 0.884653747 0.880261898]
FastEstimator-Eval: step: 984; epoch: 163; focal_loss: 0.0005124; l1_loss: 0.0301284; total_loss: 0.0306408; 
FastEstimator-Train: step: 984; focal_loss: 0.0004055; l1_loss: 0.0316203; total_loss: 0.0320258; examples/sec: 32.0; progress: 82.0%; 
FastEstimator-Train: step: 985; focal_loss: 0.0002933; l1_loss: 0.0227162; total_loss: 0.0230096; examples/sec: 32.5; progress: 82.1%; 
FastEstimator-Train: step: 986; focal_loss: 0.0005895; l1_loss: 0.0349508; total_loss: 0.0355402; examples/sec: 32.1; progress: 82.2%; 
FastEstimator-Train: step: 987; focal_loss: 0.000682; l1_loss: 0.023743; total_loss: 0.024425; examples/sec: 32.3; progress: 82.2%; 
FastEstimator-Train: step: 988; focal_loss: 0.00033

FastEstimator-Train: step: 996; focal_loss: 0.0004361; l1_loss: 0.0204588; total_loss: 0.0208949; examples/sec: 32.0; progress: 83.0%; 
FastEstimator-Train: step: 997; focal_loss: 0.0004519; l1_loss: 0.0251263; total_loss: 0.0255783; examples/sec: 32.6; progress: 83.1%; 
FastEstimator-Train: step: 998; focal_loss: 0.0002649; l1_loss: 0.0194086; total_loss: 0.0196735; examples/sec: 32.4; progress: 83.2%; 
FastEstimator-Train: step: 999; focal_loss: 0.0001961; l1_loss: 0.0451895; total_loss: 0.0453856; examples/sec: 32.3; progress: 83.2%; 
FastEstimator-Train: step: 1000; focal_loss: 0.0002084; l1_loss: 0.0095798; total_loss: 0.0097882; examples/sec: 32.2; progress: 83.3%; 
FastEstimator-Train: step: 1001; focal_loss: 0.0002541; l1_loss: 0.0366024; total_loss: 0.0368565; examples/sec: 32.3; progress: 83.4%; 
[0.996795 0.992903471 0.992664754 ... 0.053617 0.0512571335 0.0504978597]
[0.959214449 0.915042758]
[0.991349936 0.98136735 0.965367675 ... 0.077465266 0.0539001524 0.0514493]
[0.919

FastEstimator-Train: step: 1012; focal_loss: 0.0002402; l1_loss: 0.0218912; total_loss: 0.0221314; examples/sec: 31.6; progress: 84.3%; 
FastEstimator-Train: step: 1013; focal_loss: 0.0003992; l1_loss: 0.0214087; total_loss: 0.0218079; examples/sec: 32.3; progress: 84.4%; 
[0.998777211 0.994294524 0.991793931 ... 0.0543783903 0.0541574061 0.0536851585]
[0.998126864 0.982479632 0.982001662 0.973354459]
[0.997649431 0.996812224 0.948853314 ... 0.0523585379 0.0507357419 0.0503874421]
[0.972418666 0.958664179 0.939477384 0.925540686 0.053442]
[0.998575747 0.99485743 0.994660378 ... 0.0528208911 0.0512529612 0.0502161384]
[0.967268944 0.92636013]
[0.993156075 0.980145 0.96842134 ... 0.135749251 0.0732949376 0.0551602542]
[0.931008458 0.93062371 0.90858984]
[0.950852334 0.928631663 0.91677928 ... 0.0694794059 0.0585950315 0.0507801473]
[0.973861516 0.973652124 0.951243162 ... 0.0712149739 0.0538214743 0.0510072112]
[0.995548129 0.98947978 0.973397791 ... 0.920421 0.157217681 0.156938672]
[0.

[0.97965008 0.97929883 0.951482475 0.92953521 0.905668378]
[0.946169376 0.941562951 0.937114358 0.922866106 0.914208055 0.0557510555]
[0.999071836 0.992252827 0.990837216 ... 0.0528009236 0.0524427891 0.0518265069]
[0.994203806 0.962822556 0.950416267 0.936582923 0.102259785]
[0.997210622 0.99702239 0.964310884 ... 0.0544236 0.0512115061 0.0504781604]
[0.97569859 0.961482286 0.960817933 0.937583566 0.0550815761]
[0.998828173 0.99487 0.994773149 ... 0.057831496 0.053951025 0.050950855]
[0.968694925 0.929339945]
[0.992390633 0.981626511 0.968175292 ... 0.0718601644 0.0559736192 0.0536877513]
[0.927933216 0.922405243 0.896871]
[0.955868125 0.926138401 0.924708366 ... 0.0671156645 0.0560723841 0.0529504716]
[0.977623403 0.976008117 0.963540196 ... 0.0624527931 0.0605899394 0.0593805]
[0.984116554 0.971352577 0.941106319 ... 0.858342648 0.13402018 0.0782780945]
[0.996472955 0.992553949 0.990954399 ... 0.0504122972 0.0503222048 0.0501238704]
[0.978891 0.977778554 0.975735486 ... 0.0639808178

[0.9248631 0.922335505 0.92173934 0.906282663 0.896382689 0.0563687384]
[0.999329805 0.994101763 0.993508041 ... 0.0519072413 0.0507842898 0.0506363809]
[0.996080279 0.968080878 0.947391748 0.921318173 0.0979743]
[0.998008966 0.997288465 0.953228533 ... 0.0541307032 0.0513356924 0.0512887239]
[0.976473331 0.963578224 0.962343216 0.934206665]
[0.999112844 0.996815324 0.99589777 ... 0.054446876 0.0543829501 0.0505403876]
[0.965428054 0.901393414]
[0.993909717 0.984258175 0.969554543 ... 0.0683645904 0.063857913 0.0621712804]
[0.912342906 0.909073114 0.898583531]
[0.944823861 0.916793585 0.912161827 ... 0.103150994 0.0851315558 0.0597860813]
[0.977058887 0.976176798 0.970231116 ... 0.0647547841 0.0612030625 0.0537332892]
[0.98449862 0.967917085 0.93182987 ... 0.108332485 0.0911786854 0.066110909]
[0.99730432 0.993507385 0.992193103 ... 0.0527473688 0.050457 0.0502204299]
[0.975804925 0.975721359 0.969468713 ... 0.128074944 0.07730335 0.059743762]
[0.990686297 0.919788361 0.298094094]
[0.9

[0.9973979 0.997233748 0.964444757 ... 0.0521481931 0.0519691408 0.0512999]
[0.973345757 0.963052273 0.950844109 0.917611361 0.0534599721]
[0.999230206 0.996096194 0.995823622 ... 0.0519674718 0.0517619252 0.0509726107]
[0.972533762 0.903024673]
[0.992974162 0.979554653 0.9713341 ... 0.0763351917 0.0575474501 0.0569527447]
[0.919188738 0.914989233 0.911106348]
[0.953430295 0.935216784 0.926241517 ... 0.0706892312 0.0506110787 0.0504923165]
[0.980948627 0.970191479 0.962477684 ... 0.0630600154 0.0559602976 0.0534963906]
[0.99053371 0.980034 0.94910264 ... 0.897099 0.123606116 0.110646337]
[0.996332407 0.993434429 0.991652 ... 0.0564774871 0.0542211831 0.0501496196]
[0.974349141 0.972078562 0.968316436 ... 0.15008983 0.0935572684 0.0569135547]
[0.986255527 0.898531 0.269768476]
[0.994748652 0.977309108 0.975004 ... 0.892649055 0.0524658561 0.0516456664]
[0.965612531]
[0.979616165 0.979038417 0.96524179 ... 0.0513460338 0.0509076118 0.0508337319]
[0.973913789 0.972252131 0.942583203 ... 0

[0.975497 0.91794]
[0.993739605 0.977100134 0.969733953 ... 0.0736436546 0.0665171742 0.0560541153]
[0.937812328 0.932341933 0.927023053]
[0.953803897 0.93892765 0.936814845 ... 0.10090965 0.0806000233 0.0679352283]
[0.97721529 0.976297 0.970689178 ... 0.0682659745 0.0638000071 0.0532950461]
[0.991286397 0.982503176 0.957021356 ... 0.899774194 0.126107723 0.0941292644]
[0.997501791 0.993994832 0.993249893 ... 0.0569611788 0.0535824 0.0524053276]
[0.974723637 0.972013593 0.970196784 ... 0.15179345 0.079400748 0.0503405929]
[0.989311218 0.90819931 0.277479738]
[0.995056093 0.977268815 0.974778175 ... 0.92861867 0.894518614 0.0516808927]
[0.954551458]
[0.983312488 0.977702141 0.965306878 ... 0.0534710288 0.0520528853 0.0517279804]
[0.970039248 0.955344856 0.937042892 ... 0.886612475 0.640746713 0.0606476963]
[0.963027477]
[0.9993 0.95152843 0.202760905]
[0.990979195 0.990930915 0.98563838 ... 0.0544178784 0.0527929962 0.0504693389]
[0.993940234 0.993804216 0.984887 ... 0.0537514687 0.0523

[0.983539402 0.976738155 0.972765803 ... 0.115266919 0.0849086344 0.0660150051]
[0.990755916 0.984455228 0.963570416 ... 0.90372479 0.120969623 0.0735875666]
[0.997497559 0.993643403 0.992222846 ... 0.0516170859 0.0507531762 0.050552547]
[0.974889398 0.973722458 0.973303795 ... 0.125145286 0.0740614831 0.054071784]
[0.991475701 0.926344216 0.319675237 0.0534306169]
[0.994843245 0.974055052 0.971219897 ... 0.912039816 0.0613766611 0.0515283942]
[0.959061146]
[0.983350635 0.978821337 0.965793669 ... 0.0549486 0.0525002778 0.0505225062]
[0.974224746 0.960082293 0.952778935 ... 0.679761827 0.0581150353 0.0545330048]
[0.976155221]
[0.999509 0.95206213 0.199294418]
[0.988668799 0.988489926 0.985591888 ... 0.0542000532 0.0541402698 0.0529330969]
[0.995265 0.994299352 0.988517284 ... 0.0553509295 0.0542103052 0.0517367721]
[0.987884283 0.977796793 0.973509192 ... 0.074953258 0.0575661063 0.051704675]
[0.967386484 0.961598516 0.960731387 ... 0.140045106 0.0529548526 0.0519749522]
[0.973952174]


[0.979003251 0.977587581 0.974831522 ... 0.112606525 0.0746539533 0.0515412688]
[0.994459748 0.937552691 0.35363704]
[0.994242132 0.976241827 0.973953485 ... 0.926225781 0.0579358935 0.0525268316]
[0.943209469]
[0.987177491 0.984319568 0.970167875 ... 0.05215469 0.0508452654 0.0504122376]
[0.974866688 0.963385701 0.94635278 ... 0.0790320933 0.0594228506 0.0521400869]
[0.964806437]
[0.999799311 0.969000459 0.228531778]
[0.99247086 0.991927803 0.990686536 ... 0.0575997829 0.0562259257 0.0533243418]
[0.99611038 0.994628787 0.991057396 ... 0.0524891019 0.0524512827 0.0501692593]
[0.986950457 0.976912141 0.975862622 ... 0.0806909502 0.0638891757 0.0603006482]
[0.968233824 0.96219033 0.957398891 ... 0.932572246 0.157403767 0.0656243265]
FastEstimator-Eval: step: 1086; epoch: 180; focal_loss: 0.0002071; l1_loss: 0.032629; total_loss: 0.0328361; 
FastEstimator-Train: step: 1086; focal_loss: 0.0003444; l1_loss: 0.0168491; total_loss: 0.0171935; examples/sec: 32.4; progress: 90.5%; 
FastEstimato

[0.982245266 0.976283371 0.951018333 ... 0.721278608 0.063839823 0.0521264374]
[0.957693815]
[0.999631882 0.965135455 0.191378117]
FastEstimator-Eval: step: 1098; epoch: 182; focal_loss: 0.0001902; l1_loss: 0.038629; total_loss: 0.0388192; 
FastEstimator-Train: step: 1098; focal_loss: 0.0001579; l1_loss: 0.0476138; total_loss: 0.0477717; examples/sec: 32.1; progress: 91.5%; 
FastEstimator-Train: step: 1099; focal_loss: 0.0001406; l1_loss: 0.0432512; total_loss: 0.0433919; examples/sec: 32.2; progress: 91.6%; 
FastEstimator-Train: step: 1100; focal_loss: 0.0002008; l1_loss: 0.0200927; total_loss: 0.0202935; examples/sec: 32.3; progress: 91.7%; 
FastEstimator-Train: step: 1101; focal_loss: 9.16e-05; l1_loss: 0.0271924; total_loss: 0.0272841; examples/sec: 31.8; progress: 91.8%; 
FastEstimator-Train: step: 1102; focal_loss: 0.0003646; l1_loss: 0.0212213; total_loss: 0.0215859; examples/sec: 32.3; progress: 91.8%; 
FastEstimator-Train: step: 1103; focal_loss: 0.0001309; l1_loss: 0.0224022;

FastEstimator-Train: step: 1112; focal_loss: 9.62e-05; l1_loss: 0.0405096; total_loss: 0.0406058; examples/sec: 32.3; progress: 92.7%; 
FastEstimator-Train: step: 1113; focal_loss: 0.0001747; l1_loss: 0.061086; total_loss: 0.0612608; examples/sec: 32.3; progress: 92.8%; 
FastEstimator-Train: step: 1114; focal_loss: 0.0001899; l1_loss: 0.0213555; total_loss: 0.0215454; examples/sec: 32.1; progress: 92.8%; 
FastEstimator-Train: step: 1115; focal_loss: 0.0004136; l1_loss: 0.056185; total_loss: 0.0565986; examples/sec: 32.3; progress: 92.9%; 
[0.991731584 0.982443333 0.978622556 ... 0.0542204976 0.0522482693 0.0506058633]
[0.979296565 0.962187648 0.929576874 0.927333 0.900490165 0.71164465]
[0.964522839]
[0.998788714 0.961121798 0.169803649]
[0.990660608 0.988942146 0.987617195 ... 0.0524192452 0.0514372587 0.0507677794]
[0.994952321 0.990675807 0.987447083 ... 0.058129102 0.0565679967 0.0515610576]
[0.981408834 0.976102591 0.969596744 ... 0.870614052 0.10806188 0.0648639202]
[0.965067506 

FastEstimator-Train: step: 1127; focal_loss: 0.0002033; l1_loss: 0.0393629; total_loss: 0.0395662; examples/sec: 32.3; progress: 93.9%; 
[0.979026437 0.978224635 0.976018667 ... 0.159323066 0.147960782 0.072881788]
[0.994373322 0.946536422 0.361951292]
[0.994770527 0.975131869 0.974339187 ... 0.927633464 0.466511279 0.0528027713]
[0.932950914]
[0.99371 0.982533097 0.968942285 ... 0.0545597076 0.0515218675 0.0500796735]
[0.979062796 0.976475775 0.934532166 ... 0.887889862 0.0667182207 0.0502744019]
[0.9729321]
[0.999801278 0.979069769 0.282854974]
[0.99235487 0.987377346 0.982801318 ... 0.0545117855 0.0539544523 0.052411586]
[0.997598648 0.993895948 0.99240768 ... 0.0537181795 0.052647084 0.050246805]
[0.985259 0.980351329 0.978707433 ... 0.1257146 0.077908814 0.0553744435]
[0.966330767 0.949512959 0.940811455 ... 0.833883643 0.11563009 0.0671325922]
[0.97183305]
[0.976937532 0.974295914 0.934026361]
[0.999933958 0.999501109 0.998473227 ... 0.0622288287 0.0590079129 0.0577479]
[0.996412

[0.997939706 0.964075327 0.432060242 0.0758928955]
[0.993163645 0.974785805 0.970183134 ... 0.95092988 0.929253697 0.453071266]
[0.958298922]
[0.994701087 0.982873619 0.974188328 ... 0.0526577234 0.0519064963 0.0502671]
[0.986220837 0.973052144 0.97065 ... 0.919258714 0.829324 0.0635236502]
[0.979602277]
[0.999515235 0.948327303 0.210002571]
[0.991563439 0.989540875 0.981672525 ... 0.0572307408 0.0564315915 0.0539262891]
[0.997857809 0.994366825 0.992323637 ... 0.057859987 0.0576592088 0.0543296337]
[0.9747504 0.974741697 0.969414771 ... 0.0695302188 0.0573330522 0.0502076447]
[0.977609754 0.974825382 0.965416431 ... 0.0708728731 0.0580393374 0.0554314554]
[0.969732106]
[0.99464047 0.986959219 0.974684417 0.0609720349]
[0.999918 0.999571681 0.998620868 ... 0.0612441897 0.0543892682 0.0511691868]
[0.996902764 0.985441267 0.975919962 ... 0.0525900126 0.0506213307 0.0501526594]
[0.993602037 0.987188816 0.972336531]
[0.996555507 0.994232774 0.994110525 ... 0.0522467494 0.0518474877 0.05176

[0.983158946 0.972241163 0.939984262 0.939568698 0.909360349 0.775012493]
[0.958786428]
[0.997584343 0.885712445 0.16134271]
[0.994644642 0.993539274 0.984738588 ... 0.0565697253 0.0514858961 0.0504267514]
[0.996638536 0.990379214 0.989850879 ... 0.056817472 0.0506723523 0.0505039692]
[0.973508894 0.969504416 0.963210404 ... 0.0803506076 0.0566682518 0.0522883832]
[0.97749877 0.966279805 0.954695463 ... 0.931790352 0.109916657 0.0628148913]
[0.965817451]
[0.975215733 0.961176515 0.917844892]
[0.999911427 0.999411285 0.998465419 ... 0.0634129345 0.0539101362 0.0503132939]
[0.994571686 0.985456705 0.978732765 ... 0.0549059212 0.0532291532 0.0504509509]
[0.989554286 0.986525297 0.968378782]
[0.996119559 0.99494791 0.994476557 ... 0.0552400649 0.0537348688 0.0524884462]
[0.971186101 0.940359354 0.923476458]
[0.989211559 0.958190143]
[0.994078279 0.993657827 0.993646801 0.990189552 0.956918359 0.874670386]
[0.998555422 0.996017277 0.993659377 ... 0.0538450778 0.0519611835 0.050337404]
[0.99

[0.98393774 0.981217742 0.978955925 ... 0.0700246692 0.0515356064 0.0503374934]
[0.977268279 0.972717166 0.968426585 ... 0.936736822 0.181967407 0.0570483208]
[0.973815501]
[0.981061935 0.973714828 0.94465661]
[0.999934196 0.999610662 0.998555183 ... 0.0677610338 0.0584693849 0.0504846871]
[0.995257735 0.991573334 0.983921707 ... 0.052028358 0.0509494245 0.0500200391]
[0.991757035 0.982370555 0.966526866]
[0.996196389 0.995723605 0.994330287 ... 0.0523805618 0.0521193743 0.0500293672]
[0.975750446 0.96510309 0.937152386 0.0534216166]
[0.987708 0.96109736]
[0.996453047 0.996215105 0.994590759 0.994522 0.97932744 0.915057421]
[0.998929739 0.998684883 0.996688545 ... 0.0535434186 0.052767247 0.0517692566]
[0.997540951 0.983913898 0.974987388 ... 0.0559244454 0.0557602048 0.0518254042]
[0.997828722 0.993316412 0.985303223 ... 0.0565785766 0.0547170043 0.0518681109]
[0.99481976 0.982507348 0.95204854]
[0.994388342 0.990576148 0.98789537 ... 0.0551533103 0.0551151037 0.0506641865]
[0.9969357

[0.96345377]
[0.983006954 0.977073848 0.94418788]
[0.999937296 0.999645472 0.998596787 ... 0.0625954866 0.05954808 0.0548291802]
[0.995919228 0.991513491 0.982761145 ... 0.0530097187 0.0510219634 0.0504653752]
[0.992566347 0.984474361 0.963393867]
[0.99559617 0.994524 0.994067073 ... 0.0529994071 0.0525803566 0.0503200889]
[0.983132064 0.970396 0.949117541 0.0545772314]
[0.98913157 0.962095499]
[0.996260226 0.995428205 0.993688 ... 0.976883948 0.913204193 0.20473218]
[0.998783529 0.998165 0.996455431 ... 0.0528102219 0.0520303547 0.0517666936]
[0.998225927 0.987273574 0.980788 ... 0.0552553833 0.0528133214 0.050604254]
[0.997650385 0.992910624 0.982821822 ... 0.0692884 0.0595223308 0.0502953529]
[0.99400425 0.982848883 0.949568629]
[0.994124293 0.989774346 0.987185 ... 0.0584331155 0.0579452813 0.050322175]
[0.997216821 0.989451349 0.984675288 ... 0.0531401038 0.0509673953 0.050344497]
[0.996676803 0.984623671]
[0.99909544 0.99688518 0.996670663 ... 0.0570357144 0.0564675927 0.05477574

[0.982882 0.965803146 0.937761188]
[0.990714192 0.962858617]
[0.995649219 0.995360315 0.994889 0.993571758 0.966434121 0.929196835]
[0.999231 0.997624636 0.996624649 ... 0.057516396 0.0531213 0.0506055057]
[0.998515 0.989513636 0.982176661 ... 0.0542086065 0.0510974526 0.0503168106]
[0.997651041 0.99350369 0.984591722 ... 0.0620988 0.0539366901 0.052472353]
[0.99292171 0.984896779 0.941773295]
[0.995464802 0.990967274 0.990533 ... 0.0635235 0.0601339042 0.0532009304]
[0.997146606 0.990137577 0.985755444 ... 0.0553256869 0.0514213741 0.0506465435]
[0.997453332 0.986898303]
FastEstimator-ModelSaver: Saving model to /data/hsiming/mscoco_model/retinanet_best_total_loss.h5
FastEstimator-Eval: step: 1188; epoch: 197; focal_loss: 0.0001074; l1_loss: 0.0072549; total_loss: 0.0073624; 
FastEstimator-Train: step: 1188; focal_loss: 0.0001246; l1_loss: 0.0138892; total_loss: 0.0140137; examples/sec: 31.7; progress: 99.0%; 
FastEstimator-Train: step: 1189; focal_loss: 0.0001591; l1_loss: 0.0105975;

[0.996474743 0.995357275 0.994942784 0.994439 0.964081526 0.937477291]
[0.999315 0.998096 0.99711442 ... 0.0580728054 0.0549633205 0.0507517457]
[0.998321 0.987276316 0.97950381 ... 0.0716424 0.0667195618 0.0579317212]
[0.997702 0.993004084 0.984800816 ... 0.0601166189 0.0516582429 0.051309824]
FastEstimator-Eval: step: 1200; epoch: 199; focal_loss: 9.52e-05; l1_loss: 0.0075625; total_loss: 0.0076577; 
FastEstimator-Finish: step: 1200; total_time: 508.51 sec; retinanet_lr: 0.0002; 
